### ISSUE TITLE
Capabilities seems to be invalid

### ISSUE THREAD

**Issue by rafaelborja** [Mariano-Github/Edge-Drivers-Beta#1]
Capability not working on app. When using edge:create it complains about missing "name". 

https://github.com/Mariano-Github/Edge-Drivers-Beta/blob/dba52ae1edb7e1191620b41bf15b91de7e65df24/zigbee-light-multifunction-v3/Capabilities/circadian.json#L1

**Comment by Mariano-Github** [comment]
I don't quite understand what you mean.

That .json file, is a sample to create the circadian ability presentation.

What is not working in the app?

**Comment by rafaelborja** [comment]
This error when executing. Logs for smartthings edge:capability command will follow

![Screenshot_20211117-203651_SmartThings](https://user-images.githubusercontent.com/5069188/142335307-f6f0c380-39b1-4dc0-a9af-eebe12381a3e.jpg)

**Comment by Mariano-Github** [comment]
This could happen with some models of zll bulbs.

Did you try to reboot the hub or turn it off? it may be necessary the first time you install a device, for the custom capabilities to run correctly

**Comment by rafaelborja** [comment]
Same issue. Firmware 38.* can be the problem
