### ISSUE TITLE
Fingerbot Plus

### ISSUE THREAD

**Issue by rtorchia** [Mariano-Github/Edge-Drivers-Beta#101]
Just bought a fingerbot plus (zigbee) from Temu and added your driver.
And it works! Thanks for this driver!!!!

Just a few issues I've noticed:
1) It comes up as "Fingerboot Plus" (typo I'm guessing)
2) It's UI (presentation) has an off/on switch. A momentary switch for this device would work much better.

**Comment by Mariano-Github** [comment]
"It comes up as "Fingerboot Plus" (typo I'm guessing)"

Fixed

"It's UI (presentation) has an off/on switch. A momentary switch for this device would work much better."

When it works as a momentary push button, the state returned by the device is once On and once Off and this could not be done with a momentary switch feature.
