### ISSUE TITLE
Add contact mc

### ISSUE THREAD

**Issue by omgkielb** [Mariano-Github/Edge-Drivers-Beta#102]
Not sure if this one is possible to get added 
Copied these out of the “thing” driver, if they seem incorrect, any guidance would be awesome. 

Id: feibit/FB56-DOS06HM1.3
Label: Feibit/ Open Closed Sensor
Model: FB56-DOS06HM1.3
manufacturer: Feibit,co.lt

Manufacturer: Feibit,co.ltd
Model: FB56-DOS06HM1.3
FingerPrinted_EndPoint.Id: 0x01
App Version: OxOC
ZCL Version: 0x01
Network ID: OxBBCB
Zigbee EUI: 00124B001C4CCAB5
Device ID: 317a0830-d691-4152-808b-2d28643bf4ed

**Comment by Mariano-Github** [comment]
I need to see the rest of the information, clusters and endpoints of the device

**Comment by omgkielb** [comment]
Sorry, full details below

DeviceInfo:
Manufacturer: Feibit,co.ltd
Model: FB56-DOS06HM1.3
FingerPrinted_EndPoint.Id: 0x01
App Version: 0x0C
ZCL Version: 0x01
Network ID: 0xBBCB
Zigbee EUI: 00124B001C4CCAB5
Device ID: 317a0830-d691-4152-808b-2d28643bf4ed

Server Cluster:
Ep: 0x01={ 0000,0500,0000,0000 }

Client Clusters:
Ep: 0x01={ 0000,0006,0009,0001,0502,0500 }

Signal Metrics:
LQI: 178 .... RSSI: -90 dbm
DeviceInfo:
Manufacturer: Feibit,co.ltd
Model: FB56-DOS06HM1.3
FingerPrinted_EndPoint.Id: 0x01
App Version: 0x0C
ZCL Version: 0x01
Network ID: 0xBBCB
Zigbee EUI: 00124B001C4CCAB5
Device ID: 317a0830-d691-4152-808b-2d28643bf4ed

Server Cluster:
Ep: 0x01={ 0000,0500,0000,0000 }

Client Clusters:
Ep: 0x01={ 0000,0006,0009,0001,0502,0500 }

Signal Metrics:
LQI: 176 .... RSSI: -89 dbm

**Comment by Mariano-Github** [comment]
Hi, 
Added to this driver version

```
───────────────────────────────────────────────────
 Name         Zigbee Contact Mc
 Version      2023-11-08T09:39:58.360851032        
───────────────────────────────────────────────────
- id: "Feibit/FB56-DOS06HM1.3"
    deviceLabel: Open/Closed Sensor
    manufacturer: Feibit,co.ltd
    model: FB56-DOS06HM1.3
    deviceProfileName: contact-battery-profile
```

**Comment by omgkielb** [comment]
Amazing, updated and it’s all working properly! Thank you so much!
