### ISSUE TITLE
Motion sensor finger frint add plz

### ISSUE THREAD

**Issue by jinharu777** [Mariano-Github/Edge-Drivers-Beta#104]
Device Information:
Manufacturer:
TZ3000_If56vpxi
Model: TS0202
FingerPrinted_EndPoint.ld:
0x01
App Version: 0X46
ZCL Version: 0x03
Network ID: OxD512
Zigbee EUI:
A4C1389EBBF6D5A7
Device ID: 4ac59138-cfa9
4ebd-b030-eea6d96074a0
Server Cluster:
Ep: 0x01-t
0001,0500,0003,0000
Client Clusters:
Ep: 0x01-1
1000,0006,0019,000A

**Comment by Mariano-Github** [comment]
Added to this driver version
`───────────────────────────────────────────────────
 Name         Zigbee Motion Sensor Mc
 Version      2023-11-07T17:51:50.498133509        
───────────────────────────────────────────────────
- id: "_TZ3000_If56vpxi/TS0202"
    deviceLabel: TS0202 Motion Sensor
    manufacturer: _TZ3000_If56vpxi
    model: TS0202
    deviceProfileName: motion-battery
`

**Comment by jinharu777** [comment]
I installed that

Name

Zigbee Motion Sensor Mc

Description

Devices Supported: https://github.com/Mariano-Github/Edge-Drivers-Beta/blob/main/zigbee-motion-sensor-v4/fingerprints.yml

Permissions

zigbee: Enable full access to Zigbee actions


But still name is Zigbee Thing

**Comment by jinharu777** [comment]
Oh,, i had a mistake.
Manufacturer:
TZ3000_If56vpxj
no "i"  
"j" is correct.

Network ID: 0xB24B

That is corrent..

I'm very sorry.

**Comment by Mariano-Github** [comment]
Hi,

fixed in this driver version
```
───────────────────────────────────────────────────
 Name         Zigbee Motion Sensor Mc
 Version      2023-11-08T12:24:20.0639909
───────────────────────────────────────────────────
```

**Comment by jinharu777** [comment]
Thanks to your help. i'm beginner. so I don't know where can I download that version zigbee motion sensor mc
https://api.smartthings.com/invitation-web/accept?id=6b68563b-1905-4654-8d2b-e677a2997424

This link. > available drivers > Zigbee Motion Sensor Mc 

I installed but didn't work.

**Comment by Mariano-Github** [comment]
Pair device with driver zigbee thing Mc, to see complete fingerprints

**Comment by jinharu777** [comment]
very good!!! it works!!
