### ISSUE TITLE
Can I have access to the Z-Wave Switch and Childs Mc source code?

### ISSUE THREAD

**Issue by ecarlotti** [Mariano-Github/Edge-Drivers-Beta#107]
First of all, thanks for your outstanding work on Edge drivers. 

I'm trying to write some drivers myself, and I'm particularly interested in the presentation settings I found in your Z-Wave Switch and Childs Mc driver. Here on GitHub, only the fingerprints.yml file is published, and I'm wondering if it would be possible for me to have access to the full source code for that.

Three things are of interest:
  1. To be able to group child devices in a Multi-Tile component;
  2. The ability to create/delete individual child devices
  3. The settings configuration for allowing the usage of on-off switches for custom settings

Thanks in advance for any help you can give me on that.

Kind regards,
/Edson Carlotti

**Comment by Mariano-Github** [comment]
Hi,
I do not have the zwave codes published, but you can see all this information in the Zigbee Multi Switch and Child Mc driver.
The creation of child devices is identical for all zwave and zigbee drivers

The creation of presentations with multiple tiles, Groups, is common for all smartthings profiles, both zigbee, zwave and Lan

You have examples of presentations with simple and multiple mosaics in the "presentations" folder in the Zigbee Multi Switch and Child Mc drivers.

The smartthings documentation also explains how to create them:
https://developer.smartthings.com/docs/devices/configurations-and-presentations/device-configurations

If you have any questions that I can clarify, you can ask me

**Comment by ecarlotti** [comment]
Hi Mariano,

That is awesome! I can look at that code for everything I need for my devices.
Thanks a lot for your help and direction.
