### ISSUE TITLE
Smoke detector fingerprint information

### ISSUE THREAD

**Issue by seonghobae** [Mariano-Github/Edge-Drivers-Beta#108]
![image](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/8172694/8ae328c2-df3a-48ef-936b-969706d189f3)

Hello, 
Can you check and add this fingerprint to a driver? 

Best regards,
Seongho

**Comment by seonghobae** [comment]
Note: this device similar with https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3395

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version
You need uninstall device and reinstall with this driver version installed in you hub

```
─────────────────────────────────────────────────── 
 Name         Zigbee Smoke/CO Detector Mc
 Version      2023-12-11T11:33:13.45669849
───────────────────────────────────────────────────
- id: "_TZ3000_hl7yraue/TS0205"
    deviceLabel: Smoke Detector
    manufacturer: _TZ3000_hl7yraue
    model: TS0205
    deviceProfileName: smoke-battery
```

**Comment by seonghobae** [comment]
I have a question: This sensor disconnects from Hub v3 frequently, can you guess what's happening? 

Best regards,
Seongho

**Comment by Mariano-Github** [comment]
Some devices of this model TS0205 are not configured correctly to report periodically and are displayed offline.

Uninstall the device
Install this new version of the driver
Pair the device again with this version so that it is configured correctly

```
───────────────────────────────────────────────────
 Name         Zigbee Smoke/CO Detector Mc
 Version      2023-12-15T20:55:36.379203344        
───────────────────────────────────────────────────
```

**Comment by seonghobae** [comment]
Good! However, After I reconnect that with reinstall the driver, I cannot retrieve any information from smoke detector that displays as online.

**Comment by Mariano-Github** [comment]
It should work, try reinstalling it or reboot the hub

**Comment by seonghobae** [comment]
After waiting for 24 hours, it worked perfectly, I'm monitoring instabilities. I don't know why that happened. ;)

**Comment by seonghobae** [comment]
Device still goes to offline frequently if I don’t have any smoke detection events until I push the test button on my device.

**Comment by Mariano-Github** [comment]
Put it online and in the details view open the battery graph, in hours and capture every few hours the battery event arrives.

Like in this example, which is every 6 hours.

**Comment by seonghobae** [comment]
![image](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/8172694/768bafa3-14c6-47e4-9270-58bb98ed43be)

**Comment by Mariano-Github** [comment]
Sorry, these TS0205 devices only cause problems working with smartthings.

I use the Heiman HS1SA-E and they work perfectly. There are also other models that work well with smartthings

**Comment by seonghobae** [comment]
In 2023-12-11T11:33:13.45669849 version, I can retrieve battery information...

**Comment by Mariano-Github** [comment]
This driver version is as  same of 2023-12-11T11:33:13.45669849

There is nothing in all versions that prevents its operation, but smartthings requires the device to periodically send messages to the Hub and it does not have it and will appear offline every x hours

```
───────────────────────────────────────────────────
 Driver Id    a2f7ec78-14c8-492d-9965-7544b0fc3b68 
 Name         Zigbee Smoke/CO Detector Mc
 Package Key  zigbee-smoke-detector-heiman
 Version      2023-12-19T15:22:35.940921544        
───────────────────────────────────────────────────
```
