### ISSUE TITLE
Somfy Sonese 28 Driver

### ISSUE THREAD

**Issue by Tegguy** [Mariano-Github/Edge-Drivers-Beta#109]
Would it be possible to add a profile for the Somfy Sonese 28 Zigbee roller shade motor? The generic driver works but it's inverted (open vs closed) and also doesn't show battery percentage or anything.

Thank You

**Comment by Mariano-Github** [comment]
This device model is not in the driver and is paired as a generic device and that is why it works poorly.

Send me the fingerptints, manufacturer and model from my.smartthings.com, advanced users or Pair it with my zigbee thing Mc driver and post a screenshot

**Comment by Tegguy** [comment]
Here is this as well I hope it helps

DeviceInfo: <table style='font-size:75%'> <tbody><tr> <th align=left></th> <td><em style= 'font-weight: bold;'> Manufacturer: </em>SOMFY<BR><em style= 'font-weight: bold;'> Model: </em>Sonesse 28 WF Li-Ion Roller<BR><em style= 'font-weight: bold;'> FingerPrinted_EndPoint.Id: </em>0x01<BR><em style= 'font-weight: bold;'> App Version: </em>Unknown<BR><em style= 'font-weight: bold;'> ZCL Version: </em>0x03<BR><em style= 'font-weight: bold;'> Network ID: </em>0xDDC9<BR><em style= 'font-weight: bold;'> Zigbee EUI: </em>4CC206FFFE8011DC<BR><em style= 'font-weight: bold;'> Device ID: </em>fb4e37b0-4918-42cb-9610-907db8eae5fc<BR><BR><em style='color:Red;font-weight: bold;'> Server Cluster: </em><BR><b>Ep: </b>0xE8={ 0000,0001,0003,0019 }<BR><b>Ep: </b>0x01={ 0000,0003,0004,0005,0020,0102 }<BR><BR><em style='color:Green;font-weight: bold;'> Client Clusters: </em><BR><b>Ep: </b>0xE8={ 0003,0019 }<BR><b>Ep: </b>0x01={ 0003 }<BR><BR><em style='color:Blue;font-weight: bold;'> Signal Metrics: </em><BR><em style= 'font-weight: bold;'> LQI: </em>198 .... <em><b>RSSI: </em></b>-75 dbm<BR></td></tr></tbody></table>

**Comment by Mariano-Github** [comment]
Hi,
Added to this driver version

You need install this driver version from my channel in your Hub
Uninstall device a add device with this driver version to device configure

```
───────────────────────────────────────────────────
 Driver Id    e7070ea0-2ed9-4802-b7e7-5912a75f20fa 
 Name         Zigbee Window Treatment Mc
 Package Key  zigbee-window-treatment-v1
 Version      2023-12-12T22:31:28.747796089        
───────────────────────────────────────────────────
- id: "SOMFY/Sonesse 28 WF Li-Ion Roller"
    deviceLabel: SOMFY Window Treatment
    manufacturer: SOMFY
    model: Sonesse 28 WF Li-Ion Roller
    deviceProfileName: window-treatment-profile
```

**Comment by Tegguy** [comment]
Thank you thos appears to be working better. Just curious is is possible to pull battery level or anything from thos device? I honestly have no idea how these work so if it's a crazy question please just say

**Comment by Mariano-Github** [comment]
Hi,
I assigned it to the same profile as other Somfy models and I didn't realize that the profile doesn't show battery.
I have changed it to a profile with battery.

You have to uninstall the device
Delete the previous driver and reinstall this version from my channel

Reinstall the device with this new version so that it is configured correctly

```
───────────────────────────────────────────────────
 Driver Id    e7070ea0-2ed9-4802-b7e7-5912a75f20fa 
 Name         Zigbee Window Treatment Mc
 Package Key  zigbee-window-treatment-v1
 Version      2023-12-13T12:40:24.785040014        
───────────────────────────────────────────────────
- id: "SOMFY/Sonesse 28 WF Li-Ion Roller"
    deviceLabel: SOMFY Window Treatment
    manufacturer: SOMFY
    model: Sonesse 28 WF Li-Ion Roller
    deviceProfileName: window-treatment-battery
```

**Comment by Tegguy** [comment]
Thank you for this I just tried it out and the battery bar shows but I get a message "this device  hasn't updated all of it's status information yet" 

I'll be honest I don't even know if this device would report battery information but I would think it would

**Comment by Tegguy** [comment]
Scratch that it now populated! Thank you
