### ISSUE TITLE
Multi-Title Switch don´t go back to Single-Title Switch

### ISSUE THREAD

**Issue by albertovm** [Mariano-Github/Edge-Drivers-Beta#11]
Hello Mariano,

I did select a 2 gang switch as Multi-Title and later back to Single-Title, but the icon in the app still as Multi-Title.
Even when I selected another driver (Zigbee Thing Mc) the button still with Multi-Title appearance, but without switch button.
Is this something in my app or a know issue? Thanks!

Imagem to Single-Title and Thing drivers:

![image](https://user-images.githubusercontent.com/4246424/182379496-d28b3305-c58d-498e-a4ad-4f6aec6c1984.png)
![image](https://user-images.githubusercontent.com/4246424/182379556-8f66a873-d9de-4090-adf2-ba96d83e0bf9.png)

**Comment by veonua** [comment]
force-close the app after restart the icon will be updated

**Comment by albertovm** [comment]
Android devices you need to force close apps, but iOS app has no "force close". When you close the app it just closes. So it appears to be a bug with iOS app only?

**Comment by veonua** [comment]
i am on Ios , when you on the task selector screen just swipe up to force
close the app

**Comment by Mariano-Github** [comment]
It works fine for me with android.
It may be that when you make a driver change, the tile you have chosen in preferences is not displayed, although I think I already fixed that in a previous version

**Comment by Mariano-Github** [comment]
Make the tile change again in preferences. The profile change is only executed when clicking on save and if there is a change of value in the preference.

The fact that the preference shows a value does not guarantee that the profile change has been executed.
