### ISSUE TITLE
Aqara Temperature Sensor Reads 0 Then Immediately Updates Again to Correct Temp

### ISSUE THREAD

**Issue by StarScream159** [Mariano-Github/Edge-Drivers-Beta#111]
Hi Mariano,

I came across your [post here](https://community.smartthings.com/t/aqara-temperature-sensor-problem-it-goes-instantly-to-0-c-and-comes-back-to-normal/270950) about how you were going to implement a possible fix like Veonua did.

However veonua's driver was [showing the problem](https://github.com/veonua/SmartThingsEdge-Xiaomi/issues/18) so I decided to install and try yours to see if you had it fixed.

I just had it flash to zero for an update and then immediately update again to the correct temp..

The problem is this is triggering some automations.

Do you know why it is showing zero and then updating correctly? Did your fix of ignoring zero values if the previous value wasn't around zero not work?

Thanks!

**Comment by Mariano-Github** [comment]
Hi,

The github code was not updated.

Nobody who asked me told me that it didn't work well, but when I reviewed the code I saw an error and I corrected it. Thanks

Only works for manufacturer== "LUMI" and model== "lumi.weather"

This driver version fix it

```
─────────────────────────────────────────────────────────
 Name         Zigbee Temp Sensor and Child Thermostat Mc 
 Version      2024-01-04T10:04:05.829046739
─────────────────────────────────────────────────────────
```

**Comment by StarScream159** [comment]
I assume because manufacturer== "LUMI" this will not work for the Aqara/Xiaomi devices? Could you add in support for them too?

**Comment by Mariano-Github** [comment]
Aqara, xioami are trademarks. What the driver recognizes is the manufacturer and model recorded in its firmware, in this case LUMI

You can view the manufacturer and model code of your device at my.smartthings.com, advanced users.

As far as I know, the problem only affects the Aqara model, which I wrote to you

**Comment by StarScream159** [comment]
Oh, I understand about trademarks vs. manufacturer. Thanks for pointing that out. I checked under advanced users and I can confirm it shows as "lumi.weather" for model and manufacture code is "LUMI".

With that it seems like your manufacturer== "LUMI" will work. I see your commit/change and will test it and update this ticket.

Thanks.

**Comment by StarScream159** [comment]
I haven't had anymore false 0's since this change. I believe this has been fixed now. Thank you. This can be closed.
