### ISSUE TITLE
Request for adding Paulmann Bulb

### ISSUE THREAD

**Issue by xXxXJohn312** [Mariano-Github/Edge-Drivers-Beta#112]
Hey, 
I have a light bulb made by Paulmann (Paulmann 29159) it should have a range of 2200k to 5500k, but in the smartthings app it starts at 2700. with your driver it is unchanged. would it be possible to add the bulb?

![Screenshot_20240118_022531_SmartThings](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/156975258/94fd9c0f-dc17-4d4d-904f-d8c20ee238a5)

this is a screenshot from your thing mc.
the manufacturer is
Paulmann Licht GmbH

Would be really thankful if you could add it :)

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version

```
───────────────────────────────────────────────────
 Driver Id    bb1b3fd4-dcba-4d55-8d85-58ed7f1979fb 
 Name         Zigbee Light Multifunction Mc        
 Package Key  Zigbee_Light_Multifunction_v6.2      
 Version      2024-01-18T14:33:49.297802183        
───────────────────────────────────────────────────
- id: "Paulmann/CCT"
    deviceLabel: Paulmann Light CCT
    manufacturer: Paulmann Licht GmbH
    model: CCT
    deviceProfileName: level-colortemp-2200-5500
```

**Comment by xXxXJohn312** [comment]
Thank you so much for the quick reply!
