### ISSUE TITLE
Add Fingerprint for Moes blinds driver

### ISSUE THREAD

**Issue by mikegron** [Mariano-Github/Edge-Drivers-Beta#113]
Hi,
Would it be possible to add the following fingerprint for Moes Blinds Driver which is supposed to work with Tuya? :

<table style='font-size:75%'> <tbody><tr> <th align=left></th> <td><em style= 'font-weight: bold;'> Manufacturer: </em>_TZE200_zah67ekd<BR><em style= 'font-weight: bold;'> Model: </em>TS0601<BR><em style= 'font-weight: bold;'> FingerPrinted_EndPoint.Id: </em>0x01<BR><em style= 'font-weight: bold;'> App Version: </em>0x48<BR><em style= 'font-weight: bold;'> ZCL Version: </em>0x03<BR><em style= 'font-weight: bold;'> Network ID: </em>0xA29E<BR><em style= 'font-weight: bold;'> Zigbee EUI: </em>3410F4FFFE721D9A<BR><em style= 'font-weight: bold;'> Device ID: </em>4c363960-3c9c-4c20-b234-24b575a4ad6b<BR><BR><em style='color:Red;font-weight: bold;'> Server Cluster: </em><BR><b>Ep: </b>0x01={ 0000,0004,0005,EF00 }<BR><BR><em style='color:Green;font-weight: bold;'> Client Clusters: </em><BR><b>Ep: </b>0x01={ 0019,000A }<BR><BR><em style='color:Blue;font-weight: bold;'> Signal Metrics: </em><BR><em style= 'font-weight: bold;'> LQI: </em>202 .... <em><b>RSSI: </em></b>-79 dbm<BR></td></tr></tbody></table>

Thanks!

**Comment by Mariano-Github** [comment]
Hi,

Sorry, this device use cluster EF00 and not works with my driver

It can works with iquix driver 

https://github.com/iquix/ST-Edge-Driver/tree/master/tuya-window-shade

Edge Driver Installation Channel URL : https://bestow-regional.api.smartthings.com/invite/qWjB0pNyY62y

**Comment by mikegron** [comment]
Thank you for the quick response, I'll look into that!
