### ISSUE TITLE
Fingerprint request: IKEA bulb LED2201G8

### ISSUE THREAD

**Issue by MrLunar** [Mariano-Github/Edge-Drivers-Beta#115]
Hello :wave:

Please can support be added for the following new IKEA lightbulb to Zigbee Light Mutifunction:

```
Manufacturer: IKEA of Sweden
Model: TRADFRI bulb E27 WS globe 1055lm
Profile: level-colortemp-2200-4000
```

Thanks for everything!

**Comment by Mariano-Github** [comment]
> Manufacturer: IKEA of Sweden
> Model: TRADFRI bulb E27 WS globe 1055lm
> Profile: level-colortemp-2200-4000

Hello,

Added to this driver version

Uninstall device with App
Re-install device with App and this driver version to device configure

You Do not perform a driver change from other driver

```
───────────────────────────────────────────────────
 Driver Id    bb1b3fd4-dcba-4d55-8d85-58ed7f1979fb 
 Name         Zigbee Light Multifunction Mc        
 Package Key  Zigbee_Light_Multifunction_v6.2      
 Version      2024-04-11T19:57:04.678068138        
───────────────────────────────────────────────────
- id: "IKEA/bulb LED2201G8"
    deviceLabel: IKEA Bulb
    manufacturer: IKEA of Sweden
    model: TRADFRI bulb E27 WS globe 1055lm
    deviceProfileName: level-colortemp-2200-4000
```

**Comment by MrLunar** [comment]
Working perfectly. Thank you!
