### ISSUE TITLE
zwave-drivers/zwave-siren-mc/fingerprints/fingerprints.yml Neo Coolcam Siren missing features

### ISSUE THREAD

**Issue by SmartHomeAu** [Mariano-Github/Edge-Drivers-Beta#117]
Dear Mario,

It appears that Neo Coolcam Siren with manufature id: 0x0258 and product id: 0x1028 is listed as deviceProfileName: alarm-battery.

However, I believe it should be the same as deviceProfileName: coolcam-alarm-battery.

As it currently stands, it missing the ability to change key settings, including tone selection, duration, etc.

Thanks :)

**Comment by Mariano-Github** [comment]
Hello,

Is this model similar to the others Neo Coolcam?

**Comment by SmartHomeAu** [comment]
Hi Mario,

Thanks for getting back to me.  Yes, it is identical.

Please let me know if you require any further info.

Thanks again and all the best,

 	
SmartHome
p: 1300 650 136 (+61 3 8658 4289) <tel:1300 650 136> 
w: www.smarthome.com.au <http://www.smarthome.com.au/>

**Comment by Mariano-Github** [comment]
Hi,

I need comfirm fingerprints: ?
manufacturerId:0x0258
productType: 0x0600
productId: 0x1028

**Comment by SmartHomeAu** [comment]
Hi Mario,

Please see below..

Manufacturer ID: 0258-0600-1028

Product Type: 0600

Product ID: 0600-1028

I hope this helps and thanks again.

All the best,

Brad

 	
SmartHome
p: 1300 650 136 (+61 3 8658 4289) <tel:1300 650 136> 
w: www.smarthome.com.au <http://www.smarthome.com.au/>

**Comment by Mariano-Github** [comment]
Hi Brad,

Added to this driver version, try if it works

Regards
```
───────────────────────────────────────────────────
 Name         Z-Wave Siren Mc
 Version      2024-05-24T08:02:11.114487962        
───────────────────────────────────────────────────
- id: 0258/0600/1028
    deviceLabel: NEO Coolcam Siren
    manufacturerId: 0x0258
    productType: 0x0600
    productId: 0x1028
    deviceProfileName: coolcam-alarm-battery  # changed from alarm-battery
```

**Comment by SmartHomeAu** [comment]
Thanks so much Mario… working perfectly.  A small donation has been made in appreciation of your efforts :)

**Comment by Mariano-Github** [comment]
Thanks Brad
