### ISSUE TITLE
Please add motion sensor, fingerprint is tze200_bh3n6gk8

### ISSUE THREAD

**Issue by allmnet** [Mariano-Github/Edge-Drivers-Beta#118]
Hello,
Could you add Tuya motion sensor?

Product name: 
    zigBee human motion sensor
Product model:
    ZM-35ZH-Q
Fingerprint: 
    tze200_bh3n6gk8

production link is 
https://www.aliexpress.com/item/1005006897171226.html

![image](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/9440111/3259fc8c-c4bc-4ab7-9d3e-3c636b6f7e0c)

**Comment by Mariano-Github** [comment]
Sorry i forgot this!

I need the model TS0202???
