### ISSUE TITLE
Please add a fingerprint of the water valve

### ISSUE THREAD

**Issue by NovermberRain77** [Mariano-Github/Edge-Drivers-Beta#119]
Hello?
Please add a water valve finger printer.
Model name: TS0601
Model code:_TZE200_arge1ptm

**Comment by Mariano-Github** [comment]
Hi,

Thus device uses Tuta EF00 clusters and does not work with my driver

**Comment by NovermberRain77** [comment]
Hello, please add a finger print for the carbon monoxide detector

**Comment by NovermberRain77** [comment]
Thank you for your reply. This is a carbon monoxide detector.
-----Original Message-----

**Comment by Mariano-Github** [comment]
That is a water valve and I already answered that at the time.
