### ISSUE TITLE
feibit zigbee-smoke-co-detector

### ISSUE THREAD

**Issue by FFicca** [Mariano-Github/Edge-Drivers-Beta#122]
Hi Mariano, can you add to Edge-Drivers-Beta/zigbee-smoke-co-detector/fingerprints.yml the device below?

Manufacturer Code: feibit
Model: FNB56-GAS05FB1.4

Thank you,

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version

You need uninstall device
Install this driver version in your Hub
Pair device with with this driver version, you do not perform a driver change from zigbee thing

I don't know if it will work well
```
───────────────────────────────────────────────────
 Driver Id    a2f7ec78-14c8-492d-9965-7544b0fc3b68 
 Name         Zigbee Smoke/CO Detector Mc
 Version      2024-08-19T20:54:02.425672381        
───────────────────────────────────────────────────
- id: "FNB56-GAS05FB1.4/feibit"
    deviceLabel: feibit Gas Sensor
    manufacturer: feibit
    model: FNB56-GAS05FB1.4
    deviceProfileName: gas-detector
```

**Comment by FFicca** [comment]
Thank you sir!
