### ISSUE TITLE
Sunricher HK-SENSOR-4IN1-A not reporting temperature

### ISSUE THREAD

**Issue by CharlieWorthley** [Mariano-Github/Edge-Drivers-Beta#123]
I am trying out a new Sunricher/HK-SENSOR-4IN1-A sensor and everything else seems fine, but it is not reporting the temperature. Is there a chance there is an issue with the driver, or is it more likely to be a defective device?

In case it's relevant, I did factory reset and re-add the device just in case it would make a difference.

![Screenshot_20240814_164038_SmartThings](https://github.com/user-attachments/assets/4690d1e6-e1e9-4916-8a09-a7d5b9fc37eb)
![Screenshot_20240814_164052_SmartThings](https://github.com/user-attachments/assets/15f33dda-0c9f-499a-bf16-bc58eb2802b3)
![Screenshot_20240814_164124_SmartThings](https://github.com/user-attachments/assets/c8d5e3cb-8263-450f-bdd9-6b53367fd79e)
![Screenshot_20240814_164143_SmartThings](https://github.com/user-attachments/assets/6ed1b5c9-ebf4-4a1a-a795-9276f17d4a5d)

**Comment by Mariano-Github** [comment]
If it doesn't report temperature, it may not have been configured correctly during installation.
It seems that you have already reinstalled it, but I would do it again and with the device close to the hub.

**Comment by CharlieWorthley** [comment]
Interesting, I wasn't aware it's possible for a device to only partially
connect to a hub.

My first two attempts were sitting next to the hub, but I tried again per
your suggestion, and it still isn't reporting the temperature after a third
reset and reconnect.

Sense you don't seem to think the driver could be the problem, I have
ordered a replacement unit. I will update in a few days after I have tried
that one.

**Comment by CharlieWorthley** [comment]
Update: I received the replacement unit (I still have the old one too FYI) and I am having the same issue. Neither device will report the temperature.

I'm not sure if there's something that can be adjusted in the driver, but please let me know if there's anything I can do to assist.

**Comment by Mariano-Github** [comment]
Hi,
Are those the fingerprints of your device?

manufacturer: Sunricher
model: HK-SENSOR-4IN1-A

**Comment by Mariano-Github** [comment]
Try with this driver version

```
───────────────────────────────────────────────────
 Name         Zigbee Motion Sensor Mc
 Version      2024-08-27T19:45:05.910700009
───────────────────────────────────────────────────
```

**Comment by Mariano-Github** [comment]
I understand that it should work and I close the issue

**Comment by CharlieWorthley** [comment]
Hi, yes confirmed, both sensors are now reporting the temperature with the
new driver. Thanks so much!

- Charlie Worthley

(Sent via mobile)
