### ISSUE TITLE
Sinope Thermostat

### ISSUE THREAD

**Issue by mgpauly** [Mariano-Github/Edge-Drivers-Beta#124]
I have a Sinope Thermostat (for baseboard heaters) installed in SmartThings.  I am trying to change the time format on the device from 24h to 12h AM/PM. In the 'Settings' I can change the time format from 24h to 12h AM/PM, but it has no effect on the display. It stays at the 24h format.   I downloaded your 'Zigbee Thermostat MC' driver, but there is no listing for 'Settings'.   Can you do an update on your Driver to accommodate this?

Thank you for all the work you have put into these Drivers.   I, and many others appreciate your commitment.

TIA

**Comment by Mariano-Github** [comment]
Hi,
I don't know which model you are referring to, what fingerprints?.

In the driver there are 3 profiles of Sinope thermostats, which have the time format setting in the preference settings.
