### ISSUE TITLE
multi-control association

### ISSUE THREAD

**Issue by Jmo07** [Mariano-Github/Edge-Drivers-Beta#131]
@Mariano-Github Hi, was wondering if you have any thing that does the same as the following for 1 to 4 gangs zigbee light switches?

https://moeshouse.com/blogs/news/how-to-get-multi-control-association-in-smart-life-app?srsltid=AfmBOop52JqsZjPtp0oM1MeSh9x-jGGP4IhGrcXE9buTCwFhgiyHv41d

I love the drivers however i have multiple 3 way switches and when done via automations they end up in a loop or strobing.

**Comment by Mariano-Github** [comment]
Hi,
I don't know what you really want to do
If it is a multi-gang switch, with the driver, you can control them all in the same tile, choosing the multi-tile profile or manage them all at the same time with a single switch and you can also create independent devices for each gang.
![Screenshot_20220218-114649](https://github.com/user-attachments/assets/a93961ec-db5b-4b2f-88ea-66cc349f14dd)
![Screenshot_20220921-194225](https://github.com/user-attachments/assets/33331f7b-7868-4484-819a-b4a9c6edb96c)

Can you associate several independent switches to control them from a single switch?
That can be done in the smartthings app by creating a group of lights

**Comment by Jmo07** [comment]
My hallway has:
3 x 1 gang switches (outside each bedroom)
1 x 2 gang switch (with 1 gang hallway and the other the kitchen lights)

what I’d like is if I use any of the hallway gangs to turn the light on, all other gangs set to on too. That way if I use a different switch to turn the lights off all gangs also switch off. 

Basically 4 gangs (each set up as their own switch) mirror each other. 

A lighting group doesn’t work for this. I want to be able to use switch A to turn the lights on and switch B to turn them off. 

The wifi switches I used to have worked well by setting up the multi association (link above). Zigbee is better but I’m unable to have multiple switches control the same light.

**Comment by Mariano-Github** [comment]
Sorry,

That would be a request to be implemented by smartthings in its App, not to be implemented in a specific driver.
Something similar to light groups, but with multiple control to one light in the group instead of control of the entire group at same time
