### ISSUE TITLE
Routine(automation) issue

### ISSUE THREAD

**Issue by 7destiny** [Mariano-Github/Edge-Drivers-Beta#16]
In the routine, there is no separate selection menu to turn on/off the main switch and other switches, and there is a problem that the main switch is unconditionally turned on. Each switch needs a separate menu to turn it on and off.
![14EFB235-843A-439F-B89C-BBBB625C63B6](https://user-images.githubusercontent.com/90086961/187429136-64e575f4-a770-4155-9a90-be367f7b4382.png)
![9A8F1BE9-11FC-4F1D-923B-6C7BDE20FFAD](https://user-images.githubusercontent.com/90086961/187429164-13514370-dd54-4f2a-be37-ed5d5057d642.jpeg)

**Comment by Mariano-Github** [comment]
Hi,

There is a ploblem with ios app last versión.
It was repoted.

In Android app works fine
