### ISSUE TITLE
Please add fingerprint for IKEA GU10 Bulb

### ISSUE THREAD

**Issue by veonua** [Mariano-Github/Edge-Drivers-Beta#2]
```
-id: “IKEA/TRADFRIbulbGU10WS345lm”
  deviceLabel: IKEA GU10 Bulb
  manufacturer: IKEA of Sweden
  model: TRADFRIbulbGU10WS345lm
  deviceProfileName: level-colortemp-2700-6000

```

https://zigbee.blakadder.com/Ikea_LED1923R5.html

**Comment by veonua** [comment]
Ep#1 device_id:0x010C profile_id:0x0104 model:'TRADFRIbulbGU10WS345lm' manufacturer:'IKEA of Sweden' Client clusters:[OTAUpgrade, ] Server clusters:[Basic, Identify, Groups, Scenes, OnOff, Level, ColorControl, TouchlinkCommissioning, 0xFC57, ]
Ep#242 device_id:0x0061 profile_id:0xA1E0 Client clusters:[0x0021, ] Server clusters:[0x0021, ]


Zigbee message: < ZigbeeMessageRx || type: 0x00, < AddressHeader || src_addr: 0x40B7, src_endpoint: 0x01, dest_addr: 0x0000, dest_endpoint: 0x01, profile: 0x0104, cluster: Groups >, lqi: 0xB8, rssi: -54, body_length: 0x0005, < ZCLMessageBody || < ZCLHeader || frame_ctrl: 0x19, seqno: 0x55, ZCLCommandId: 0x02 >, < GetGroupMembershipResponse || capacity: 0xFF, group_list_length: 0x00 > > >

**Comment by Mariano-Github** [comment]
Hi Andrew

Is the correct model without spaces?

model: TRADFRIbulbGU10WS345lm

or with spaces as others ikea bulb models?

model: TRADFRI bulb GU10 WS 345lm

Thanks

**Comment by veonua** [comment]
without spaces.

**Comment by Mariano-Github** [comment]
Ok Thanks

**Comment by veonua** [comment]
the dimmer does not get a confirmantion.
when I select level in the app the device acts accordingly. but the waiting wheel stays forever.

**Comment by Mariano-Github** [comment]
Well, I don't know if it hasn't been installed properly or if I need a reboot of the hub and clear the cache.

The ones I have installed with this version, are not ikea, but they work fine.
