### ISSUE TITLE
Fingerprint update request: _TZ3000_typdpbpg/TS011F

### ISSUE THREAD

**Issue by ibr23** [Mariano-Github/Edge-Drivers-Beta#22]
Hi,

can you please update the fingerprint. This device is a single Zigbee 3.0 plug with power metering:

manufacturer: _TZ3000_typdpbpg
model: TS011F

Thanks

**Comment by Mariano-Github** [comment]
Hi Ian

Added to this driver version
`┌─────────────┬──────────────────────────────────────┐
│ Name        │ Zigbee Switch Power Mc               │
│ Version     │ 2022-09-16T12:26:00.033541953        │
└─────────────┴──────────────────────────────────────┘
  - id: "TS011F/_TZ3000_typdpbpg"
    deviceLabel: TS011F Plug
    manufacturer: _TZ3000_typdpbpg
    model: TS011F
    deviceProfileName: switch-power-energy-plug
`

**Comment by ibr23** [comment]
Hi Mariano,

this works great.

Just some tiles are missing titles:

![Screenshot_20220917-120650~2](https://user-images.githubusercontent.com/23491477/190836505-2a0ce967-8ebd-424d-a1b4-409e6d5624ac.png)

Thanks!

**Comment by Mariano-Github** [comment]
Titles mising is a problem of Apps. 
yesterday it got worse, hopefully they fix it soon

**Comment by ibr23** [comment]
Thanks
