### ISSUE TITLE
Fingerprint update request _TZ3000_cfnprab5/TS011F

### ISSUE THREAD

**Issue by ibr23** [Mariano-Github/Edge-Drivers-Beta#23]
Hi,

this device is a powerboard with 4 switchable plugs and 1 group of switchable USB ports (1 switch for 4 USB).

Currently when I add it, it is recognised by your Zigbee Mult Switch Mc driver, but only 4 switches in total are added (main+3).

Can you please update the fingerprint to make this a 5 switch plug.

Manufacturer
- _TZ3000_cfnprab5
Model:
- TS011F

Thanks
Ian

![Screenshot_20220916-131945~2](https://user-images.githubusercontent.com/23491477/190550159-4a83c37e-563d-4589-97ae-026dc8f26976.png)

**Comment by Mariano-Github** [comment]
Hi  Ian
Do the 4 switches shown work independently for you?

I was trying to fix it and it was impossible, I couldn't find the reason why they all turn on and off at the same time.

I don't have access to the CLI now, a couple of days I will.

with what you tell me I do it

**Comment by ibr23** [comment]
Hi Mariano,

sorry, I did not explain very clearly. This is the Zigbee powerboard image: https://www.aliexpress.com/i/4000504463608.html

The four existing switches for the four power outlets all work correctly (each works independetly of each other).

I just need you to add one more switch. This will switch the four USB outlets. There board has only one endpoint that controls all four USB outlets. 

Thank you in advance.
Ian

**Comment by Mariano-Github** [comment]
I'm glad they work independently.
A few days ago to another user both worked at the same time and I left it as impossible.
https://community.smartthings.com/t/beta-zigbee-edge-driver-compatible-with-lidl-ecosmart-osram-smartthings-others/231689/2317?u=mariano_colmenarejo

I will add the 5th switch as son is posible and you try it

**Comment by ibr23** [comment]
Hi Mariano,

thanks, that works great. All 5 outlets are switchable independently.

![Screenshot_20220917-120023~2](https://user-images.githubusercontent.com/23491477/190836224-02215215-6f7a-4cdc-adc5-4603aea13b8c.png)

One question: Is it possible to edit the name of the **Switch-2**, **Switch-3** etc? I would like to change them to _TV_, _DVD_, etc

**Comment by Mariano-Github** [comment]
Sorry, user can not change the labels of the components.
It has been requested and I don't know if they will

**Comment by ibr23** [comment]
Thanks

**Comment by ibr23** [comment]
Can you also add the following:

Manufacturer:
- _TYZB01_vkwryfdr
Model:
- TS0115

This is physically identical to the device above. It has 4 power outlets and 1 USB.

However, when I built the Groovy DTH, the USB endpoint is 7.

i.e.
EP1 = Power outlet
EP2 = Power outlet
EP3 = Power outlet
EP4 = Power outlet
**EP7 = USB outlets**

Thanks
Ian

**Comment by Mariano-Github** [comment]
I need to see the clusters list to match the profile

**Comment by ibr23** [comment]
Hi Mariano,

here are the clusters:

![Screenshot_20220921-093612~2](https://user-images.githubusercontent.com/23491477/191390529-8517b050-ad8e-4d65-9bd3-a62346072b23.png)

Thanks

**Comment by Mariano-Github** [comment]
Hi

Give me some time I am modifying this driver to add other functions

**Comment by Mariano-Github** [comment]
Hi

Added to this driver version
```
┌─────────────┬──────────────────────────────────────┐
│ Name        │ Zigbee Multi Switch Mc               │
│ Version     │ 2022-09-22T21:13:14.703540351        │
└─────────────┴──────────────────────────────────────┘
```
and this other driver with childs devices
```
┌─────────────┬──────────────────────────────────────┐
│ Name        │ Zigbee Multi Switch and Childs Mc    │
│ Version     │ 2022-09-22T21:13:20.327906873        │
└─────────────┴──────────────────────────────────────┘
```
```
  - id: "TS0115/_TYZB01_vkwryfdr"
    deviceLabel: TS0115 Switch
    manufacturer: _TYZB01_vkwryfdr
    model: TS0115
    deviceProfileName: five-outlet
```

**Comment by ibr23** [comment]
Hi Mariano,

thanks for adding TS0115/_TYZB01_vkwryfdr.

The 4 outlets (Main, switch2, switch3, switch4) = EP1, EP2, EP3, EP4 are working fine.
The USB (switch5) is not working. This is **EP7** (not EP5 which is more logical).

Can you please check this for me.

Thanks
Ian
