### ISSUE TITLE
Fingerprint update request: IKEA of Sweden/TRADFRI bulb E27 WS opal 1000lm

### ISSUE THREAD

**Issue by ibr23** [Mariano-Github/Edge-Drivers-Beta#24]
Hi,

can you please add the following to Edge Driver Zigbee Light Multifunction Mc

- Manufacturer: IKEA of Sweden
- Model: TRADFRI bulb E27 WS opal 1000lm

I think this is the correct profile: level-colortemp-2200-4000

Thanks

![image](https://user-images.githubusercontent.com/23491477/190879407-eb7d6154-c1d3-4f29-b403-b6906ddf641a.png)

**Comment by Mariano-Github** [comment]
Hi,
Added to this driver version

```
┌─────────────┬──────────────────────────────────────┐
│ Name        │ Zigbee Light Multifunction Mc        │
│ Version     │ 2022-09-18T13:39:57.644565922        │
└─────────────┴──────────────────────────────────────┘
```

**Comment by ibr23** [comment]
Thanks, that works great!

**Comment by ibr23** [comment]
Can you please add the following:

- Manufacturer: IKEA of Sweden
- Model: TRADFRI bulb E27 W opal 1000lm

Not sure which profile is best. Can we try level-colortemp-2200-4000?

Thanks
Ian

**Comment by ibr23** [comment]
Hi Mariano,

The second request was for a different TRADFRI bulb. It is type W opal (the original request was for type WS opal).

Can you please add TRADFRI bulb E27 **W** opal 1000lm

Thanks

**Comment by Mariano-Github** [comment]
Hi
Added to this driver version

```
┌─────────────┬──────────────────────────────────────┐
│ Name        │ Zigbee Light Multifunction Mc        │
│ Version     │ 2022-09-22T20:49:06.53560497         │
└─────────────┴──────────────────────────────────────┘
  - id: "TRADFRI bulb E27 W opal 1000lm"
    deviceLabel: IKEA Bulb E27 WS
    manufacturer: IKEA of Sweden
    model: TRADFRI bulb E27 W opal 1000lm
    deviceProfileName: level-colortemp-2200-4000
```
