### ISSUE TITLE
Fingerprint update request: Konke motion detector

### ISSUE THREAD

**Issue by ibr23** [Mariano-Github/Edge-Drivers-Beta#25]
Hi,

can you please add this device:

![Screenshot_20220918-103237~2](https://user-images.githubusercontent.com/23491477/190880806-d8d5ade5-6be0-4a9c-bc6c-12233ed2de5b.png)

Thanks

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version
```
┌─────────────┬──────────────────────────────────────┐
│ Name        │ Zigbee Motion Sensor Mc              │
│ Version     │ 2022-09-18T13:45:21.832421532        │
└─────────────┴──────────────────────────────────────┘
```

**Comment by ibr23** [comment]
Hi Mariano,

I have tried the driver. The driver is recognised when I add the device. 

After pairing, it immediately shows there is motion detected, but the motion stays active and never goes inactive (no motion).

![Screenshot_20220921-105802~2](https://user-images.githubusercontent.com/23491477/191391073-e0cfcc4f-1022-4e4c-bdf3-ce83955e7396.png)

It also doesn't show the battery level:

![Screenshot_20220921-105909~2](https://user-images.githubusercontent.com/23491477/191391132-5506c8bd-cf44-4698-bc73-dc1512ebdb20.png)

Let me know if you need me to generate a log etc.

Thanks
Ian

**Comment by Mariano-Github** [comment]
You may need to reset the movement, there are devices that work like this.
now i change it

the battery, you may need the logs to see if the device uses voltage or percentage attribute.
by default the driver is using percentage

**Comment by Mariano-Github** [comment]
Added 30 sec timeout for motion and battery voltage battery handler

```
┌─────────────┬──────────────────────────────────────┐
│ Name        │ Zigbee Motion Sensor Mc              │
│ Version     │ 2022-09-21T20:39:06.556072305        │
└─────────────┴──────────────────────────────────────┘
```
