### ISSUE TITLE
Fingerprint zigbee-valve-st-mc

### ISSUE THREAD

**Issue by toma9996** [Mariano-Github/Edge-Drivers-Beta#26]
Hi Mariano,

can you please add this fingerprint for irrigation valve:

Product page: https://wooxhome.com/products-c10/other-c4/woox-r7060-smart-garden-irrigation-control-p61

application: 45
endpointId: 01
firmwareFullVersion: 00000045
firmwareImageType: 5634
firmwareManufacturerCode: 4098
**manufacturer: _TZ3210_eymunffl
model: TS0101**
zigbeeNodeType: SLEEPY_END_DEVICE

I suppose bolded part is fingerprint.

Thanks,
Tomislav

**Comment by Mariano-Github** [comment]
Need the cluster list to see with profile can match

**Comment by toma9996** [comment]
I hope this help:
https://githubmemory.com/repo/JohanBendz/com.tuya.zigbee/issues/62

and cluster info on tuya development page for water valve:
https://developer.tuya.com/en/docs/iot/Zigbee-Water-valve-controller-access-standard?id=Kbahvojbqzvgl#title-0-Zigbee%20protocol%20version

**Comment by Mariano-Github** [comment]
Hi,

Give me some time I am modifying other driver to add other functions and this device need create a new profile

**Comment by toma9996** [comment]
no hurry.

**Comment by Mariano-Github** [comment]
Hi

Added to this diver version
```
┌─────────────┬──────────────────────────────────────┐
│ Name        │ Zigbee Valve Mc                      │
│ Version     │ 2022-09-22T22:25:09.390789294        │
└─────────────┴──────────────────────────────────────┘
  - id: "_TZ3210_eymunffl/TS0001"
    deviceLabel: Water Valve
    manufacturer: _TZ3210_eymunffl
    model: TS0101
    deviceProfileName: water-valve-battery
```

**Comment by toma9996** [comment]
I will try to check today. Thank you.

**Comment by toma9996** [comment]
Hi, it's working perfectly.

Cheers

**Comment by ibbr0** [comment]
Is there information somewhere that I have missed about installation/use. I have used your channel invite to enroll a hub and install Z-Wave Device Config Mc. I hope to configure Jasco/GE zwavew dimmers which are currently using default 'Zwave switch' edge driver. I don't see any options or evidence that your driver is installed/available. Although I feel like an idiot, I'm a programmer, and can probably figure it out if pointed in the right direction. Thank you.

**Comment by Mariano-Github** [comment]
In the device detail view, menu three points on the top right, option driver and then use another driver.
Select the Z-Wave Device Config Mc

**Comment by ibbr0** [comment]
I dont have a driver option at all under the device detail. Do I need to be registered as a developer? I read something about that earlier when I started looking into configuration commands

**Comment by Mariano-Github** [comment]
This is due to your device not use a driver edge

**Comment by ibbr0** [comment]
thanks, i'll do some more homework.
