### ISSUE TITLE
fingerprint update please

### ISSUE THREAD

**Issue by gosimin** [Mariano-Github/Edge-Drivers-Beta#27]
Zigbee swich mc edge add fingerprint please.

2gang moes inner module

TS011F
TZ3000_pmz6mjyu

**Comment by Mariano-Github** [comment]
Hi 

Added to this driver version

───────────────────────────────────────────────────
 Driver Id    bc53adfe-d18f-4ea4-9610-6aade6696b7a 
 Name         Zigbee Switch Mc
 Package Key  Zigbee_Switch_v6.5
 Version      2022-10-01T17:22:05.863604906        
───────────────────────────────────────────────────
  - id: "TS011F/_TZ3000_pmz6mjyu"
    deviceLabel: TS011F Plug
    manufacturer: _TZ3000_pmz6mjyu
    model: TS011F
    deviceProfileName: single-switch-plug
