### ISSUE TITLE
Request Finger print : TZ3210_k1pe6ibm(Manufacturer)_TS0505B(Model)

### ISSUE THREAD

**Issue by cyj0829** [Mariano-Github/Edge-Drivers-Beta#29]
Please Make Edge Driver of Zemismart LED Strip 

TZ3210_k1pe6ibm(Manufacturer)_TS0505B(Model)

thank you

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version
Sorry,  I'm not very aware of github and I forgot

───────────────────────────────────────────────────
 Name         Zigbee Light Multifunction Mc             
 Version      2022-10-25T15:36:51.72322314
───────────────────────────────────────────────────
  - id: "_TZ3210_k1pe6ibm/TS0505B"
    deviceLabel: RGBW TS0505B
    manufacturer: _TZ3210_k1pe6ibm
    model: TS0505B
    deviceProfileName: rgbw-level-colortemp-2700-6500
