### ISSUE TITLE
Please add support for Zigbee termostat

### ISSUE THREAD

**Issue by Kjelljk** [Mariano-Github/Edge-Drivers-Beta#30]
Hi,

Please add support for termostat from Tuya / Connecte.

I belive I found some information about the thermostat in another case: https://github.com/Koenkk/zigbee2mqtt/issues/11895 :

zigbeeModel: ['hbx5cvx'],
fingerprint: [
{
modelID: 'TS0601',
manufacturerName: '_TZE200_4hbx5cvx'

**Comment by Mariano-Github** [comment]
Hi
Sorry, I don't have any driver that support thermostat devices.
My thermostat driver is for temperature sensing devices and adds virtual thermostat capabilities to them.
