### ISSUE TITLE
zwave nice gate opener (IBT4ZWAVE)

### ISSUE THREAD

**Issue by toma9996** [Mariano-Github/Edge-Drivers-Beta#31]
Hi Mariano,

could you please check for Nice gate motor opener (IBT4ZWAVE) will fit to any of zwave drivers?
The one I'm using at my home is: https://products.z-wavealliance.org/products/3837?selectedFrequencyId=1

I tested it with stock DTH Z-Wave Window Shade, stock DTH Z-Wave Basic Window Shade and it's working flawlessly. Also, I remember it was working with Fibaro FGR-223 DTH without issues.

MSR: 0441-2400-1000
manufacturer: null
networkSecurityLevel: ZWAVE_S2_FAILED

zw:L type:1100 mfr:0441 prod:2400 model:1000 ver:7.00 zwv:7.13 lib:03 cc:5E,26,85,8E,59,5A,7A,87,72,73,98,9F,6C,55,86,71,22,75,70

Thank you a lot,
Toma

**Comment by Mariano-Github** [comment]
Hi Toma,

If you say it worked with the Fibaro FGR-223 DTH, then it should work with this one.

Published in my shared channel
───────────────────────────────────────────────────
 Name         Z-Wave Window Treatment Mc
 Version      2022-10-20T19:56:52.154909047        
───────────────────────────────────────────────────
  - id: NICE/IBT4ZWAVE
    deviceLabel: NICE Door IBT4ZWAVE
    manufacturerId: 0x0441
    productType: 0x2400
    productId: 0x1000
    deviceProfileName: window-treatment-power

**Comment by toma9996** [comment]
You are great.

Beer is on me :.-) (paypal)

**Comment by Mariano-Github** [comment]
Hi 

I changed to different profile, nice-garage-door.

Try and tell me if works for you

https://community.smartthings.com/t/edge-driver-mc-z-wave-edge-drivers-and-others-with-fibaro-devices/239409/1302?u=mariano_colmenarejo
