### ISSUE TITLE
Fingerprint request: IKEA bulb

### ISSUE THREAD

**Issue by ibr23** [Mariano-Github/Edge-Drivers-Beta#34]
Hi Mariano,

hope you are well.

Can you please add the following:

- manufacturer: IKEA of Sweden
- model: TRADFRIbulbB22WSglobeopal1055lm
- zigbeeNodeType: ROUTER

Note: The model doesn't follow IKEA's usual format. 

It is a dimmable white bulb with changeable temperature.

Thanks
Ian

**Comment by Mariano-Github** [comment]
Hi

Added to this driver version
───────────────────────────────────────────────────
 Name         Zigbee Light Multifunction Mc              
 Version      2022-10-30T09:40:23.088964764        
───────────────────────────────────────────────────
  - id: "IKEA/bulbB22WSglobeopal1055lm"
    deviceLabel: IKEA Bulb
    manufacturer: IKEA of Sweden
    model: TRADFRIbulbB22WSglobeopal1055lm
    deviceProfileName: level-colortemp-2200-4000

**Comment by ibr23** [comment]
Thanks!
