### ISSUE TITLE
Fingerprint request greenwave powernode 6

### ISSUE THREAD

**Issue by KilledByAGuitar** [Mariano-Github/Edge-Drivers-Beta#35]
Hello Mariano,

Can you please add the following fingerprint for the greenwave powernode 6 NP310-F:

Id: 7472db29-706f-45a1-a12f- 5d089c6acf30
DNI: 0×3B
Manufacturer: 0x0099 
Product Type: 0x0003 
Product ID: 0x0004

It's a 6 port powerstrip which should have metering capabilities on every one of the ports, however the device handlers have always been problematic so I'd be surprised if metering actually works now.

If just the switches work I'd be happy enough.

![Screenshot_20221101-074345](https://user-images.githubusercontent.com/36461642/199175958-5cb65f3c-b958-42d4-820d-4e5fe417adf4.png)
![Screenshot_20221101-074357](https://user-images.githubusercontent.com/36461642/199175962-4023fca9-c969-4e3e-8864-f2c97be2b924.png)

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version.
Users of that brand Greenwave often complain that they do not periodically update the power and energy
───────────────────────────────────────────────────
 Name         Z-Wave Switch and Child Mc
 Version      2022-11-01T11:41:28.181456713        
───────────────────────────────────────────────────
  - id: 0099/0003/0004
    deviceLabel: Greenwave NP310-F
    manufacturerId: 0x0099
    productType: 0x0003
    productId: 0x0004
    deviceProfileName: switch-multicomponent-generic-5

**Comment by KilledByAGuitar** [comment]
I think they're also discontinued and the quality was never amazing so I wouldn't worry about it too much. Thanks for adding the fingerprint!
