### ISSUE TITLE
Request to add Sengled Bulb Fingerprint -  ‎E12-N1EW 

### ISSUE THREAD

**Issue by ViperTK** [Mariano-Github/Edge-Drivers-Beta#36]
Please add a fingerprint for Sengled Element Color Plus Bulb -  E12-N1EW https://www.amazon.com/gp/product/B092D8B6FT/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1

Data from my IDE for one of these bulbs. They're RGBW bulbs. Please let me know if any other data/info is needed on these.

**Data** 
zigbeeNodeType: NON_SLEEPY_END_DEVICE
firmwareManufacturerCode: 4448
firmwareFullVersion: 0000001E
application: 1E
endpointId: 01
firmwareImageType: 1016
manufacturer: sengled
model: E12-N1E

**Raw Description |** 
01 0104 0102 00 0C 0000 0003 0004 0005 0006 0008 0300 0702 0B05 FC03 FC04 FC13 01 0019

**Comment by Mariano-Github** [comment]
Hi

This model was added a long time ago
  - id: sengled/E12-N1E
    deviceLabel: Sengled Element Color Plus
    manufacturer: sengled
    model: E12-N1E
    deviceProfileName: rgbw-level-colortemp-2700-6500

**Comment by ViperTK** [comment]
When I search the fingerprints file for latest v6 for "E12-N1E", it cannot find it. Even tried searching for Sengled and see if I have it. Is it not added under the lights?

**Comment by Mariano-Github** [comment]
The fingerprints is in the fingerprints.yml file

**Comment by ViperTK** [comment]
yes, I couldn't see this specific one in the yaml file here:

https://github.com/Mariano-Github/Edge-Drivers-Beta/tree/main/zigbee-light-multifunction-v6)/fingerprints.yml

**Comment by Mariano-Github** [comment]
Sorry, I can't get everything updated, I just updated.
The drivers channel are updated, but I update the code from time to time

**Comment by ViperTK** [comment]
oh ok, makes sense. And no need for apologies. 
I'm sure all community members anyways appreciate the work you and other developers are doing.
