### ISSUE TITLE
Request to add Jinvoo Multiswitch fingerprint to Multiswitch-Child driver

### ISSUE THREAD

**Issue by iferlive** [Mariano-Github/Edge-Drivers-Beta#37]
Hello Mariano, please add a fingerprint for Jinvoo smart socket (multiswitch).

https://www.amazon.com/Jinvoo-Individual-switches-SmartThings-Certified/dp/B0B4W76NX6/ref=sr_1_2?crid=5BMT2S4SUOSP&keywords=jinvoo+smart+zigbee&qid=1668537607&sprefix=jinvoo+smart+zigbe%2Caps%2C261&sr=8-2

In this device the 3 ports are controllable, 2 outlets and the USB port. They work just fine in HomeAssistant but I'd rather have them configured in Smartthings.

Device data taken from IDE:

application: 43
endpointId: 01
manufacturer: _TZ3000_wc2uoeah
model: TS011F
zigbeeNodeType: ROUTER

Raw Description	01 0104 010A 01 07 0000 0003 0004 0005 0006 E000 E001 02 0019 000A

Please let me know if any further information is required.

**Comment by Mariano-Github** [comment]
Hi,

Are the 3 switches controlled independently or only 2?
I need to know if it has 2 endpoints or 3 endpoints and if they are consecutive

**Comment by iferlive** [comment]
Hello, thank you for your quick reply. 

All 3 switches are controlled independently, the 2 outlets and the USB port. I am almost 100% sure that the endpoints of the 2 outlets are consecutive, one being 01 and the other one 02. A few weeks ago I set them up with a child virtual switch in the IDE. The USB is the one I never got it working with a child device in Smartthings IDE. 
On the other hand, HA detects the 3 endpoints and controls them.

**Comment by Mariano-Github** [comment]
Hi
Added to this driver version

───────────────────────────────────────────────────
 Driver Id    540ae948-6fcc-4137-809c-875c3e186071 
 Name         Zigbee Multi Switch and Child Mc     
 Version      2022-11-15T19:59:17.536797195        
───────────────────────────────────────────────────
  - id: "_TZ3000_wc2uoeah/TS011F"
    deviceLabel: Jinvoo MultiPlug
    manufacturer: _TZ3000_wc2uoeah
    model: TS011F
    deviceProfileName: three-outlet

**Comment by iferlive** [comment]
I can confirm that the device is now fully controlable with the Multi Switch and Child driver. Thank you so much for your quick reply to my request.
