### ISSUE TITLE
Z-Wave windows treatment fingerprints

### ISSUE THREAD

**Issue by sylion** [Mariano-Github/Edge-Drivers-Beta#38]
Could you add Fingerprints for "Forest Shuttle L Z-Wave" curtain motor? It was working fine with standard Z-Wave Window Shade DTH before edge drivers released.

Screenshot from groovy page and pdf manual from manufacturer attached.
(Device don't have battery. Always knows current curtain position, even if it was changed manually without electric power) - if it's important. Let me know if you need any other info.

<img width="1459" alt="Знімок екрана 2022-11-22 о 14 47 28" src="https://user-images.githubusercontent.com/3854523/203320367-503a0567-50bb-46bd-bea0-90b4a9198f2e.png">

[download_287_Installing the FOREST SHUTTLE S-M-L  Z-wave V1_6EN.pdf](https://github.com/Mariano-Github/Edge-Drivers-Beta/files/10067560/download_287_Installing.the.FOREST.SHUTTLE.S-M-L.Z-wave.V1_6EN.pdf)

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version
Assigned to profile It seems to be more in line with what I see in your capture, without battery
───────────────────────────────────────────────────
 Driver Id    79679b70-6c89-4efa-a711-e5f6fa6f657e 
 Name         Z-Wave Window Treatment Mc
 Version      2022-11-22T17:32:28.011024722        
───────────────────────────────────────────────────
  - id: Forest Shuttle/Blind
    deviceLabel: Forest Shuttle SML
    manufacturerId: 0x0207
    productType: 0x0027
    productId: 0x0100
    deviceProfileName: window-treatment-preset-reverse

**Comment by sylion** [comment]
Thanks. It works. 

but there is few issues:
- it still show battery section.
- a warning message popup every time I open device page in TS app. 
- there is a button "Go to preset position" but no settings for it.

![IMG_5D66024FC9DC-1](https://user-images.githubusercontent.com/3854523/203413223-fcb0df2a-7ae7-48b6-8ebe-a4c0abd40f58.jpeg)

**Comment by Mariano-Github** [comment]
I have created a profile without battery
Preset values must be entered in settings

The error that appears is that it cannot update the value of some capability, it must be due to the battery "window-treatment-preset"

Try this version of the driver.
You will have to uninstall the device
delete the previous version of the driver
Install the new version
install the device

```
───────────────────────────────────────────────────
 Driver Id    79679b70-6c89-4efa-a711-e5f6fa6f657e 
 Name         Z-Wave Window Treatment Mc
 Version      2022-11-22T20:38:15.975637007        
───────────────────────────────────────────────────
  - id: Forest Shuttle/Blind
    deviceLabel: Forest Shuttle SML
    manufacturerId: 0x0207
    productType: 0x0027
    productId: 0x0100
    deviceProfileName: window-treatment-preset
```

**Comment by sylion** [comment]
Thanks again, it works perfect now.

Right now preset position is 50%, there is no settings in ST app as it was with DTH for this device. But it's not a problem at all.
