### ISSUE TITLE
Pls add Lidl switch button

### ISSUE THREAD

**Issue by sparks5737** [Mariano-Github/Edge-Drivers-Beta#41]
Hello,
can you please add Lidl switch button as follow?

Manufacturer: _TZ3000_rco1yzb1
Model: TS004F
Server Cluster: Ep: 01={ 0000,0001,0003,0004,0006,1000,E001 }
Client Clusters: Ep: 01={ 0019,000A,0003,0004,0005,0006,0008, 1000 }

Thank you.
Ondrej

**Comment by Mariano-Github** [comment]
Hi,

Sorry, I don't have any driver that works with this button, I even had one to test and I wasn't able to make it work
