### ISSUE TITLE
Please add Philio PAN11-1B drivers

### ISSUE THREAD

**Issue by KilledByAGuitar** [Mariano-Github/Edge-Drivers-Beta#42]
Hello Mariano,

Can you please add the following fingerprint for the Philio PAN11-1B. The switch works but the metering doesn't.

Id: 24420aaa-9708-451c-a3ba-9946a67ab465
DNI: 0x3D
Manufacturer: 0x013C
Product Type: 0x0001
Product ID: 0x0011
![Screenshot_20230103-072615~2](https://user-images.githubusercontent.com/36461642/210310699-bf83492e-3c3a-4ceb-92ef-1ee55dea7f76.png)

**Comment by Mariano-Github** [comment]
Hi 

Added to this driver version
Try if works

```
───────────────────────────────────────────────────
 Driver Id    5d3423d1-ce62-4ec6-bf21-53d3fe78284d 
 Name         Z-Wave Switch and Child Mc
 Version      2023-01-03T18:18:35.363908167        
───────────────────────────────────────────────────
- id: 0013C/0001/0011
    deviceLabel: Philio PAN11-1B
    manufacturerId: 0x013C
    productType: 0x0001
    productId: 0x0011
    deviceProfileName: metering-plug
```

**Comment by KilledByAGuitar** [comment]
It works like charm, thank you!
