### ISSUE TITLE
New Device for Zigbee Light Multifunction MC

### ISSUE THREAD

**Issue by IngoSmart** [Mariano-Github/Edge-Drivers-Beta#43]
Hi Mariano, 
I am complete new to the topic of Edge Driver for SmartThings, so I have to apologize for my question:
Looks that my purchased Innr Color Bulb are not exactly mentioned in your Light Multifunction MC fingerprint, and therefore might not be recorgnized by searching in ST app. You have BY 286 C, but not RB 286 C - which I have - Could that be the issue of not finding?  I have copied the data out of SmartthingsHub config which the bulb is connecting to, not using the edge driver.

Data | application: 24
endpointId: 01
manufacturer: innr
model: RB 286 C
zigbeeNodeType: ROUTER

Raw Description | 01 0104 010D 01 0A 0000 0003 0004 0005 0006 0008 0300 1000 FC57 FC82 01 0019

Hope you can help me on this; Great thanks in advance and best regards Ingo

**Comment by Mariano-Github** [comment]
Hi,
Added to this driver version
`───────────────────────────────────────────────────
 Driver Id    bb1b3fd4-dcba-4d55-8d85-58ed7f1979fb 
 Name         Zigbee Light Multifunction Mc           
 Version      2023-01-06T15:50:04.796972008        
───────────────────────────────────────────────────
- id: "innr/RB 286 C"
    deviceLabel: innr RGBW
    manufacturer: innr
    model: RB 286 C
    deviceProfileName: rgbw-level-colortemp-2700-6500
`

**Comment by IngoSmart** [comment]
Thousand thanks,.... I have the updated driver on my Smarthub and could connect via scanning the QR code
Amazing...absolut fantastic.
