### ISSUE TITLE
Please add support to Hue Smart Button

### ISSUE THREAD

**Issue by iferlive** [Mariano-Github/Edge-Drivers-Beta#44]
Hello Mariano,

Please include the Philips Hue Smart Button into the edge driver st-zigbee-button. This button does not measure temperature and I believe it only supports 1 click actions.

Manufacturer: Signify Netherlands B.V.
Model: ROM001
FingerPrinted_EndPoint.Id: 0x01
App Version: 0x02
ZCL Version: 0x02
Network ID: 0x3CF9
Zigbee EUI: 001788010803E748
Device ID: ab26634f-b55b-4fbf-8f5c-227ebe60dc48
Server Cluster: Ep: 0x01={ 0000,0001,0003,FC00,1000 }
Client Clusters: Ep: 0x01={ 0019,0000,0003,0004,0006,0008,0005,1000 }

Thanks in advance.

**Comment by Mariano-Github** [comment]
Hi,

This button does not work with the driver, it needs cluster 0500.
I don't think it will work with the stock driver either.

it looks like you can use some manufacturer specific cluster FC00

**Comment by iferlive** [comment]
Hi, thank you for your response. I will then check for other drivers with the same cluster and test. Thanks again!
