### ISSUE TITLE
eWeLink/Z102LG03-1

### ISSUE THREAD

**Issue by albertovm** [Mariano-Github/Edge-Drivers-Beta#45]
Mariano... another one. Regards.

"bulbshit": https://pt.aliexpress.com/item/1005004626576014.html?spm=a2g0o.order_list.order_list_main.87.8cb7caa4bo32ro&gatewayAdapt=glo2bra

  - id: "eWeLink/Z102LG03-1"
    deviceLabel: eWeLink Z102LG03-1
    manufacturer: eWeLink
    model: Z102LG03-1
    deviceProfileName: rgbw-level-colortemp-2700-6500

**Comment by Mariano-Github** [comment]
Hi Alberto
Added to this driver version
`───────────────────────────────────────────────────
 Driver Id    bb1b3fd4-dcba-4d55-8d85-58ed7f1979fb 
 Name         Zigbee Light Multifunction Mc             
 Version      2023-01-07T18:00:34.858795889        
───────────────────────────────────────────────────`

**Comment by Mariano-Github** [comment]
Hi Alberto
Neither do I. It's in the driver, I just checked
