### ISSUE TITLE
D-link motion sensor  DCH-B122 support

### ISSUE THREAD

**Issue by gibahjoe** [Mariano-Github/Edge-Drivers-Beta#46]
Hi,

Please add support for D-link motion sensor  DCH-B122
https://www.dlink.com/en/products/dch-b122-mydlink-smart-diy-motion-sensor

Data
------------
application: 47
endpointId: 01
manufacturer: D-Link
model: DCH-B122
zigbeeNodeType: SLEEPY_END_DEVICE

Raw Description
-----------------
01 0104 0402 01 07 0000 0001 0003 0020 0500 0B05 FC81 01 0019

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version
```
───────────────────────────────────────────────────
 Name         Zigbee Motion Sensor Mc
 Version      2023-01-07T18:08:31.869288326
───────────────────────────────────────────────────
- id: "D-Link/DCH-B122"
    deviceLabel: D-Link Motion Sensor
    manufacturer: D-Link
    model: DCH-B122
    deviceProfileName: motion-battery
```

**Comment by gibahjoe** [comment]
Thanks. It worked
