### ISSUE TITLE
Allow renaming the child switches in zigbee-multi-switch-v4-childs

### ISSUE THREAD

**Issue by sunnygoyal** [Mariano-Github/Edge-Drivers-Beta#47]
There are default names to switch-2, switch-3 ..., and there is no way to rename them.
Also allow an option to make the "All-On-All-off" toggle the primary action instead of it being the switch-1

**Comment by Mariano-Github** [comment]
Hi,
The names of the components in the multiple main device cannot be changed, they can be changed in the individual Child devices if they are created.

The order of certain cabilities cannot be changed in custom presentations, for example if there is a switch stock it puts it first.
If there is a battery, it always puts the last one

**Comment by sunnygoyal** [comment]
Thanks.
For the switch, it is possible to change the primary switch to control all the output and have the switch-1 as a secondary action. Not sure if it is possible to provide a "setting" to switch this behavior, or would it require publishing a completely different driver
