### ISSUE TITLE
Window Shade

### ISSUE THREAD

**Issue by albertovm** [Mariano-Github/Edge-Drivers-Beta#49]
Hello Mariano,
Could you try 2 devices?

Window
  - id: "_TZE200_cf1sl3tj/ZM85EL-2Z"
    deviceLabel: _TZE200_cf1sl3tj
    manufacturer: _TZE200_cf1sl3tj
    model: TS0601

Roller
  - id: "_TZE200_7eue9vhc/ZM25RZ01"
    deviceLabel: _TZE200_7eue9vhc
    manufacturer: _TZE200_7eue9vhc
    model: TS0601

**Comment by Mariano-Github** [comment]
Hi Alberto

Devices with cluster EF00 do not works with my drivers
