### ISSUE TITLE
Add Zigbee Siren _TZE204_t1blo2bj

### ISSUE THREAD

**Issue by ibr23** [Mariano-Github/Edge-Drivers-Beta#50]
Hi Mariano,

can you please add this Zigbee siren. It is just a basis siren without a switch:

Thanks
Ian

Manufacturer: _TZE204_t1blo2bj
Model: TS0601
FingerPrinted_EndPoint.Id: 0x01
App Version: 0x4A
ZCL Version: 0x03

Server Cluster:
Ep: 0x01={ 0004,0005,EF00,0000 }

Client Clusters:
Ep: 0xF2={ 0021 }
Ep: 0x01={ 0019,000A }

**Comment by Mariano-Github** [comment]
Hi,

Sorry, this device does not works with my driver, due to use cluster EF00
