### ISSUE TITLE
Request to add TH sensor with backlight

### ISSUE THREAD

**Issue by junmo-kim** [Mariano-Github/Edge-Drivers-Beta#51]
Hello! I want to request add device fingerprint to `zigbee-temp-humidity-sensor`.
Thank you for your commitment to community.

* Tuya Zigbee Temperature Humidity Sensor With Backlight https://www.aliexpress.com/item/1005003980647546.html

Mfg Code | _TZE200_whkgqxse
Model | TS0601

Below is one added to Hubitat.

https://github.com/kkossev/Hubitat/blob/main/Drivers/Tuya%20Temperature%20Humidity%20Illuminance%20LCD%20Display%20with%20a%20Clock/Tuya_Temperature_Humidity_Illuminance_LCD_Display_with_a_Clock.groovy#L182

**Comment by Mariano-Github** [comment]
Hi
Sorry, model TS0601 use cluster EF00 and not works with my driver
