### ISSUE TITLE
Request to add PIR motion sensor

### ISSUE THREAD

**Issue by sirLobito** [Mariano-Github/Edge-Drivers-Beta#52]
Hello! I want to request add device fingerprint to _Zigbee Motion Sensor Mc_ (I think, I´m new to all this world).
Thank you for your commitment to community.

Tuya PIR motion sensor [https://aliexpress.com/item/1005004845802129.html](https://aliexpress.com/item/1005004845802129.html)
Mfg Code | _TZ3000_6ygjfyll
Model | TS0202

Thanks in advance for all your help.

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version
`───────────────────────────────────────────────────
 Name         Zigbee Motion Sensor Mc
 Version      2023-01-28T09:36:46.161821631        
───────────────────────────────────────────────────
- id: "_TZ3000_6ygjfyll/Motion"
    deviceLabel: TS0202 Motion Sensor
    manufacturer: _TZ3000_6ygjfyll
    model: TS0202
    deviceProfileName: motion-battery`

**Comment by sirLobito** [comment]
Incredible work.
My biggest congrats for your work.
It's working like a charm.
Love you.
