### ISSUE TITLE
zigbee-contact-mc-v3

### ISSUE THREAD

**Issue by GP2954** [Mariano-Github/Edge-Drivers-Beta#53]
Hi Mario, Visonics MCT-350 SMA temperature reading not working. Request fix please.
Thanks

**Comment by vmarineci** [comment]
Hi Mariano
I have Visonic MCT - 370 SMA. Contact status and Battery it shows good. However the temp is not showing any value.
Please fix
![image](https://user-images.githubusercontent.com/87401439/227746508-905a60cd-270f-466e-9e2c-a38287c0301b.png)

**Comment by Mariano-Github** [comment]
Hi

There is nothing in the driver that will correctly function the temperature caability for your device.

Rather it may be a problem with your device. Try re-pairing near the Hub, so the temperature reports on the device are set up correctly again

**Comment by vmarineci** [comment]
Hi Mariano,
I’ll try to repair all sensors. However no sensor shows the temp.
Thanks for your help!

**Comment by sedy1112** [comment]
Hi Mariano
﻿below tuya door sensor exists in your finger print(in grey) but does not work. Could you please fix?

Manufacturer _TZE200_pay2byax

Model ts0601

﻿

**Comment by sedy1112** [comment]
Got it, Thanx!!
