### ISSUE TITLE
Wrong value in energy consumption for zigbee switch power MC

### ISSUE THREAD

**Issue by stain46** [Mariano-Github/Edge-Drivers-Beta#60]
![Screenshot_20230310_152659_SmartThings](https://user-images.githubusercontent.com/127474969/224241207-952d03ab-06c0-4fc7-a45d-374f979b27c0.jpg)
![Screenshot_20230310_152614_SmartThings](https://user-images.githubusercontent.com/127474969/224241233-f2142525-f3ad-4579-988b-95a146c348c3.jpg)
![Screenshot_20230310_153302_SmartThings](https://user-images.githubusercontent.com/127474969/224241258-8cdb35c5-0ce0-4a92-aac1-57f38845b216.jpg)

46.0kWh is too high value. It is just one day use.
When I checked with other edge driver, it is displayed as 460Wh.

**Comment by Mariano-Github** [comment]
HI

Change it to zigbee Thing Mc driver and change it back to zigbee Switch Power Mc so that the divisor is set to 100.
For some reason it has been deconfigured.

It would also be resolved by pairing it again

**Comment by stain46** [comment]
Hello.  Thanks for comment.
I have tried to change driver to zigbee Thing Mc and back to zigbee Switch Power Mc.
But there is no change for energy consumption.

Refer to video.

https://user-images.githubusercontent.com/127474969/224547942-aa8deb08-ed5c-44e5-a368-075ea1998a67.mp4

Repairing after deleting device also have no change.

Thanks.

**Comment by Mariano-Github** [comment]
You don't have to look at accumulated value, you have to look at how much it accumulates from now on.

You can also reset the energy value with a routine or uninstall the plug and reinstall it to reset it to 0 W/h

![Screenshot_20230106-121919](https://user-images.githubusercontent.com/74271621/224552476-72b81603-dcf5-4317-8f07-9b04fa3ec3db.png)
