### ISSUE TITLE
Request to add Aqara H1 Smart Dimmer Switch

### ISSUE THREAD

**Issue by sirLobito** [Mariano-Github/Edge-Drivers-Beta#62]
Hello! I want to request add device fingerprint to _Zigbee Multi Switch and Child Mc_ (at least that´s the driver that fits best).
Thank you for your commitment to community.

Aqara H1 Smart Dimmer Switch https://es.aliexpress.com/item/1005005253857998.html
Mfg | Aqara
Model | ZNXNKG02LM

Thanks in advance for all your help.

**Comment by Mariano-Github** [comment]
Hi,

Sorry, this device does not work with my driver

**Comment by sirLobito** [comment]
Hi Mariano
Thanks for all your help, at least this driver works like a charm with my other devices :).
If it's not to ask for too much, do you know what driver can fit this device? I've been finding a solution but all I get is to convert from 'Thing' to 'Zigbee thing'.
Once again, thanks for all.
