### ISSUE TITLE
Fibaro Smart Implant 1st virtual temp probe no value

### ISSUE THREAD

**Issue by ChrisSpray** [Mariano-Github/Edge-Drivers-Beta#69]
You driver was working brilliantly for me, with 4 external temperature probes connected.  However, sometime before 20 April 04:00 CET, the reading for the first probe in the "virtual" device had been replaced with the word "Connected".  The settings avaiable for this device  are thre same as those for the actual physical device rather than the virtual device settings shown for the other 3 probres.

**Comment by Mariano-Github** [comment]
Hi,

I don't know what could happen.
You can try to delete the virtual device of probe 1 and recreate it

**Comment by ChrisSpray** [comment]
Hi Mariano

 

Don’t know what happened, but it has sorted itself out!

 

Thanks anyway

 

Chris
