### ISSUE TITLE
Power Lost issue…

### ISSUE THREAD

**Issue by 7destiny** [Mariano-Github/Edge-Drivers-Beta#7]
After installation, turn off all switches and turn them on, after a few seconds the power is momentarily turned off and instantly restored. After that, it has been on for a long time without any problems, but if I turn off all the switches without using it and turn them on again, the problem occurs again. I'm using a 3gang _TZ3000_wyhuocal switch. What's the matter?

**Comment by Mariano-Github** [comment]
Sorry, but I don't understand the problem you describe.

What driver are you using?

**Comment by Mariano-Github** [comment]
But what problem occurs?
When you turn on all the switches, do they turn off by themselves after a while?

**Comment by 7destiny** [comment]
There is no problem after it is turned off momentarily and then restored again. However, if I turn it off and then turn it off and then use it again, the same phenomenon repeats.

**Comment by 7destiny** [comment]
I replaced it with a spare switch and there is no problem. I think the switch is broken
