### ISSUE TITLE
Please add support for zigbee switch _TZ3000_bmzfjnbp

### ISSUE THREAD

**Issue by iferlive** [Mariano-Github/Edge-Drivers-Beta#70]
Hello Mariano, one more request bro. Pease add this device fingerprint to the Zigbee-Switch driver, there are other fingerprints in the driver but none of them matches this device. Thanks in advance.

Device Information:
Manufacturer: _TZ3000_bmzfjnbp
Model: TS0011
FingerPrinted_EndPoint.Id: 0x01
App Version: 0x44
ZCL Version: 0x03
Network ID: 0xC940
Zigbee EUI: 943469FFFEB7A1BD
Device ID: 2a4e29cd-f697-4827-83de-
9f1ae4ff492c

Server Cluster:
Ep: 0x01={
0000,0003,0004,0005,0006,E000,E001 }

Client Clusters:
Ep: 0x01={0019,000A }
Ep: 0xF2={0021}

Signal Metrics:
LQI: 192.... RSSI: -65 dbm

Device:
https://www.aliexpress.com/item/1005004887397411.html?spm=a2g0o.order_list.order_list_main.17.ea0c180268h9Qc

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version

```
───────────────────────────────────────────────────
 Driver Id    bc53adfe-d18f-4ea4-9610-6aade6696b7a 
 Name         Zigbee Switch Mc
 Package Key  Zigbee_Switch_v6.5
 Version      2023-05-19T18:33:30.62112119
───────────────────────────────────────────────────
- id: "_TZ3000_bmzfjnbp/Switch"
    deviceLabel: TS0011 Switch
    manufacturer: _TZ3000_bmzfjnbp
    model: TS0011
    deviceProfileName: single-switch
```

**Comment by iferlive** [comment]
Thank you for your quick response, my switches are now working flawlessly with the updated driver. 
Cheers!
