### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Grandik7** [Mariano-Github/Edge-Drivers-Beta#73]
Hello Mariano,

I have bought 2 [lights](https://www.amazon.com.be/-/en/Connect-z-Fueva-Z-Connected-Bathroom-Controllable/dp/B09FSYBGBZ) and used your edge [drivers](https://github.com/Mariano-Github/Edge-Drivers-Beta/tree/main/zigbee-light-multifunction-v6) to connect them to the hub. One of them was connected successfully but the other one cannot be found. 

I want to ask if you can provide any hint or way how to debug it, please.

P.S. I wanted to contact you directly, but cannot find any contact info

Thank you,
Michal

**Comment by Mariano-Github** [comment]
HI Michal,

Install the **zigbee thing Mc** driver in your ub from [my channel](https://api.smartthings.com/invitation-web/accept?id=6b68563b-1905-4654-8d2b-e677a2997424) and pair the devices with this driver to see the fingerprints and be able to add them to the driver so that they can work with the driver

**Comment by Grandik7** [comment]
Hi Mariano,

thank you for quick response!

Actually I have this driver installed, but hub didn't find anything. Obviously there is something wrong with my hub as I have difficulties with other devices also. E.g. for IKEA TRADRFI switch I cannot select your Zigbee Switch driver.

**Comment by Mariano-Github** [comment]
Hi Michal

Zigbee thing Mc should pair with any zigbee device directly or be able to switch to that driver from any other.

try turning off and on again the hub or a reboot from IDE

**Comment by Grandik7** [comment]
Hi Mariano, 

 I've restarted hub several times even before, but today suddenly after restart it found that light. I've one other zigbee light from aliexpress which is still not connected bu maybe some day :) 

I just want to add that your drivers are really nice work - thank you very much!

We can close this issue.
