### ISSUE TITLE
Fingerprint for Aqara Water Leak Sensor E1

### ISSUE THREAD

**Issue by jim-liu** [Mariano-Github/Edge-Drivers-Beta#77]
I recently came across this sensor, model number SJCG13LM. According to the spec, the main difference between this and SJCG11LM is that SJCG13LM is Zigbee 3.0.

Could you add the fingerprint to the moisture sensor YML? I can also open a PR if that'd be more convenient. Thanks!

```
 - id: "Lumi/SJCG13LM"
    deviceLabel: Aqara Water Leak Sensor
    manufacturer: LUMI
    model: lumi.sensor_wleak.aq1
    deviceProfileName: moisture-battery
```

**Comment by Mariano-Github** [comment]
Until the month of August I do not have access to the CLI and my pc.
If you want you can add them to the file fingerptints.yml and create your own driver

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version
```
───────────────────────────────────────────────────
 Name         Zigbee Aqara Water Leak Sensor Mc    
 Version      2023-08-02T17:19:49.68343041
───────────────────────────────────────────────────
- id: "Lumi/SJCG13LM"
    deviceLabel: Aqara Water Leak Sensor
    manufacturer: LUMI
    model: lumi.sensor_wleak.aq1
    deviceProfileName: water-battery
```

**Comment by jim-liu** [comment]
Thanks! I only got around to test it now. I installed the **Zigbee Aqara Water Leak Sensor Mc** driver, then add SJCG13LM to my hub. Still showing up as Zigbee Thing without any available driver.

It seems that my device actually has a different model. It is showing up as `lumi.flood.acn001` under the new [Advanced User App](https://my.smartthings.com/advanced). Would you be able to include this model as well?

**Comment by Mariano-Github** [comment]
Hi,

Added to two drivers

```
───────────────────────────────────────────────────
 Name         Zigbee Aqara Water Leak Sensor Mc
 Version      2023-09-11T08:18:33.892336556
───────────────────────────────────────────────────
- id: "Lumi/SJCG13LM"
    deviceLabel: Aqara Water Leak Sensor
    manufacturer: LUMI
    model: lumi.flood.acn001
    deviceProfileName: water-battery
───────────────────────────────────────────────────
 Name         Zigbee Moisture Sensor Mc
 Version      2023-09-11T08:19:32.326969632        
───────────────────────────────────────────────────
- id: "Lumi/SJCG13LM"
    deviceLabel: Aqara Water Leak Sensor
    manufacturer: LUMI
    model: lumi.flood.acn001
    deviceProfileName: moisture-battery
```
