### ISSUE TITLE
SmartWings shade preset position still inverted

### ISSUE THREAD

**Issue by hoverlx** [Mariano-Github/Edge-Drivers-Beta#78]
My SmartWings started to run inverted yesterday with the default driver, thanks to your driver, it got fixed after I switched driver to this one. 
The only issue left is that the preset postion is still inverted. It's actually running to 3% when you set it to 97%.

**Comment by Mariano-Github** [comment]
I think the preset is defined in the default libraries.
In August when I have access to my pc and cli I will look at it.
meanwhile you can enter an inverted preset value

**Comment by Mariano-Github** [comment]
Try this driver version

```
───────────────────────────────────────────────────
 Name         Zigbee Window Treatment Mc
 Version      2023-08-02T18:39:41.585643645        
───────────────────────────────────────────────────
```
