### ISSUE TITLE
New fingerprint for Soil sensor

### ISSUE THREAD

**Issue by jamer007** [Mariano-Github/Edge-Drivers-Beta#79]
Hi, 
I have a Tuya Zigbee soil sensor, basically the same functionality as a thermostat (temp and humidity) but it is not present in your repo, can you add it?

Here is the info from the Zigbee Thing MC:
```
Manufacturer: _TZE200_myd45weu  
Model: TS0601
```
Thanks

**Comment by Mariano-Github** [comment]
Hi,

This device uses Tuya cluster EF00 and does not work with standard zigbee drivers
