### ISSUE TITLE
Fingerprints for Everspring Dimmer and HSA Dual Switch

### ISSUE THREAD

**Issue by nasrijamaluddin** [Mariano-Github/Edge-Drivers-Beta#80]
Hello Mariano (and team),

Greetings from Malaysia! Am new on smartthings and been trying out the edge drivers, particularly the beta from your channel. Take your time with these, I am aware that you won't be working in these till August.

- id: 0060/0033/0001
    deviceLabel: Everspring AD370 MOS Dimmer Module
    manufacturerId: 0x0060
    productType: 0x0033
    productId: 0x0001
    deviceProfileName: metering-dimmer

- id: 0068/0003/0015
    deviceLabel: HSA TD130X0Z2 In-wall Power Monitor Switch
    manufacturerId: 0x0068
    productType: 0x0003
    productId: 0x0015
    deviceProfileName: dual-metering-switch

Much appreciated and many thanks for your kind effort adding these to your Z-wave switch and Child MC beta driver.

[AD37020user20manual_v120finish_0708-1.pdf](https://github.com/Mariano-Github/Edge-Drivers-Beta/files/11925673/AD37020user20manual_v120finish_0708-1.pdf)
[TD130X0Z2_Manual_V1.0 for HSA_20181123 (1).pdf](https://github.com/Mariano-Github/Edge-Drivers-Beta/files/11925674/TD130X0Z2_Manual_V1.0.for.HSA_20181123.1.pdf)

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version
Try if it works

```
───────────────────────────────────────────────────
 Name         Z-Wave Switch and Child Mc
 Version      2023-08-02T17:57:08.044358763        
───────────────────────────────────────────────────
- id: 0060/0033/0001
    deviceLabel: Everspring AD370 MOS Dimmer Module
    manufacturerId: 0x0060
    productType: 0x0033
    productId: 0x0001
    deviceProfileName: metering-dimmer
  - id: 0068/0003/0015
    deviceLabel: HSA TD130X0Z2 In-wall Power Monitor Switch
    manufacturerId: 0x0068
    productType: 0x0003
    productId: 0x0015
    deviceProfileName: dual-metering-switch
```

**Comment by nasrijamaluddin** [comment]
Hi Mariano, thanks for adding the fingerprints.

I've tried the dual metering switch by first excluding the switch from my hub and reincluded in into the hub as generic Z-wave device. It's recognised correctly as HSA TD130X0Z2 In-wall Power Monitor Switch however only main and switch1 can be seen. There isn't a switch2. Going into the device settings allows creation of single device for only switch1. Crating child device to see fingerprints does indeed show 2 endpoints & command classes in device info.
![Screenshot_20230804_222920_SmartThings](https://github.com/Mariano-Github/Edge-Drivers-beta/assets/138296908/7423d9b4-3cb8-4436-aafb-a3008dfaba34)

Clicking switch1 on and off gives an expected behaviour and power/energy reporting. Main on/off remains off.

Clicking main on and off turns switch1 on and off as well with expected power/energy reporting at switch1. However power/energy reporting for mains remains zero.

As the dual metering switch is also connected to physical momentary switches, clicking the physical switch corresponding to switch1 gives an expected behaviour and power/energy reporting similar to toggling switch on and off in smartThings.

Clicking the physical momentary switch corresponding to the supposed switch2 toggles the main on and off with power/energy being reported at the main panel corresponding to the supposed switch2.

The main on/off button in the app seems to be reacting to supposed switch2 on/off state when toggled via the physical switch. Toggling the main on/off button on the app however controls the on/off state of switch1.

I hope the feedback is meaningful, do ask if more information is needed. Much thanks.

**Comment by Mariano-Github** [comment]
Hi,

With the philosophy of smartthings in edge multicomponent devices, the "mian" component in App corresponds to physical switch-1 and "switch1" comonent in App corresponds to physical switch-2.

With this version of the driver, the assignment of endpoints 1 and 2 should work fine.

You can create a separate child device for App switch1 (physical switch-2)

**Comment by nasrijamaluddin** [comment]
> Hi,
> 
> With the philosophy of smartthings in edge multicomponent devices, the "mian" component in App corresponds to physical switch-1 and "switch1" comonent in App corresponds to physical switch-2.
> 
> With this version of the driver, the assignment of endpoints 1 and 2 should work fine.
> 
> You can create a separate child device for App switch1 (physical switch-2)
> 
> ```
> ───────────────────────────────────────────────────
>  Name         Z-Wave Switch and Child Mc
>  Version      2023-08-04T15:07:02.294749264        
> ───────────────────────────────────────────────────
> ```

All is well indicated and reported in smartThings when toggling the corresponding physical switches per your explaination.. however switching the main switch on and off in the app is also switching switch1 in the app on and off (and the corresponding bulb for switch1). The corresponding bulb for main switch doesn't react when switching the main switch in the app on and off. Version of the driver has been updated, and I've also rebooted my hub. Tried excluding and reincluded the device as well. Am I missing something? Much appreciated your kind assistance.

**Comment by Mariano-Github** [comment]
Hi,

try with this driver version
```
───────────────────────────────────────────────────
 Name         Z-Wave Switch and Child Mc
 Version      2023-08-04T17:09:37.940839559        
───────────────────────────────────────────────────
```

**Comment by nasrijamaluddin** [comment]
Works perfectly now. Thank you so much for your effort!!
