### ISSUE TITLE
Power Consumption (Watts) for Thermostat Edge Driver

### ISSUE THREAD

**Issue by xmorand** [Mariano-Github/Edge-Drivers-Beta#84]
Hello, 

Looks like theses drivers work well with Stelpro Zigbee Thermostats. On the old platform before edge drivers it was possible to get the power consumption in Watts. Any plans to have this added to the thermostat edge driver ?

Thanks,

**Comment by xmorand** [comment]
Do you know how to request Smartthings to add this ?

In the meantime I explored the folder zigbee-thermostat-stock-mc in this project and trying to reverse engineer the code to add the support - are you ok if I propose a merge request for this repo?

**Comment by xmorand** [comment]
Done - https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/896

First time doing pull request for Edge Drivers - let me know if it looks good.

**Comment by Mariano-Github** [comment]
You should refer to the stock driver files, not mine.

If you reference the girhub of another driver than smartthings, they cannot merge it.

You can also do an issue as you wrote to me, instead a pull request

**Comment by xmorand** [comment]
I actually started by forking the original smartthings drivers, then incorporated the changes you made that were relevant on top of the original ones and added my own for the power metrics and home assistant compatibility - so we should be good there.
