### ISSUE TITLE
_TYZB01_dazsid15. Tuya Window Blinds Not showing closed Percentage

### ISSUE THREAD

**Issue by adrian-damaschin** [Mariano-Github/Edge-Drivers-Beta#85]
Hi there,

Been using your drivers for my window blinds from Tuya but I have 2 models.

1. Code: _TYZB01_dazsid15 ; Model TS0302
2. Code: _TZ3000_ltiqubue ; Model TS130F

The second one works perfectly but for the first one I cannot seem to use the percentage setting. if it's open its 100%, if Closed 0% and if anywhere in between it's 50%. Also messing up with the dial doesn't do anything not even 100% or 0% setting.

Is it possible to fix anything?

**Comment by Mariano-Github** [comment]
Hi,

Code: _TYZB01_dazsid15 ; Model TS0302

Need see the clusters if this device pairing it with zigbee thing mc driver.

If uses EF00 cluster then does not works with my driver

**Comment by adrian-damaschin** [comment]
![Screenshot 2023-07-25 at 14 51 44](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/24243437/ccce3abf-9c22-40bc-8325-7413f3ce5cc4)
Is this the required info ?

**Comment by Mariano-Github** [comment]
No, i need info with zigbee thing mc driver

**Comment by adrian-damaschin** [comment]
New to this, Where do i get that ?

**Comment by Mariano-Github** [comment]
In my channel

https://api.smartthings.com/invitation-web/accept?id=6b68563b-1905-4654-8d2b-e677a2997424

**Comment by adrian-damaschin** [comment]
![Screenshot 2023-07-25 at 15 02 11](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/24243437/6215563f-4b5b-4a1f-8ad7-02f4e5b4a97a)

**Comment by Mariano-Github** [comment]
I'm talking about the zigbee thing Mc driver

install it on your hub and perform a driver change to this driver

**Comment by adrian-damaschin** [comment]
![Screenshot 2023-07-25 at 15 07 26](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/24243437/d6434b6e-b652-430b-b359-4647ebb998d1)

**Comment by adrian-damaschin** [comment]
<table style='font-size:75%'> <tbody><tr> <th align=left></th> <td><em style= 'font-weight: bold;'> Manufacturer: </em>_TYZB01_dazsid15<BR><em style= 'font-weight: bold;'> Model: </em>TS0302<BR><em style= 'font-weight: bold;'> FingerPrinted_EndPoint.Id: </em>0x01<BR><em style= 'font-weight: bold;'> App Version: </em>0x42<BR><em style= 'font-weight: bold;'> ZCL Version: </em>0x03<BR><em style= 'font-weight: bold;'> Network ID: </em>0x02C7<BR><em style= 'font-weight: bold;'> Zigbee EUI: </em>BC33ACFFFE170591<BR><em style= 'font-weight: bold;'> Device ID: </em>e3892a8a-587b-4271-94ff-b7f4df316060<BR><BR><em style='color:Red;font-weight: bold;'> Server Cluster: </em><BR><b>Ep: </b>0x01={ 0004,0005,0102,0000 }<BR><BR><em style='color:Green;font-weight: bold;'> Client Clusters: </em><BR><b>Ep: </b>0x01={ 0019 }<BR><BR><em style='color:Blue;font-weight: bold;'> Signal Metrics: </em><BR><em style= 'font-weight: bold;'> LQI: </em>198 .... <em><b>RSSI: </em></b>-73 dbm<BR></td></tr></tbody></table>

**Comment by Mariano-Github** [comment]
I don't know why the open percentage doesn't work.

Until August I don't have access to the CLI and I can't do anything.

try re-pairing it from scratch to see if it sets up correctly.

**Comment by adrian-damaschin** [comment]
Did that a couple of times but ok, just let me know when you come back, it's not of urgency

**Comment by Mariano-Github** [comment]
Hi,

Added fingerprints to this driver version.
If does not work then you mus send the logs wit CLI
```
───────────────────────────────────────────────────
 Name         Zigbee Window Treatment Mc
 Version      2023-08-02T18:43:51.780312938        
───────────────────────────────────────────────────
- id: "TS0302/_TYZB01_dazsid15"
    deviceLabel: TS130F Window Treatment
    manufacturer: _TYZB01_dazsid15
    model: TS0302
    deviceProfileName: window-treatment-profile
```
