### ISSUE TITLE
Bosch ISW-ZDL1-WP11G motion sensor

### ISSUE THREAD

**Issue by Hawk15000** [Mariano-Github/Edge-Drivers-Beta#86]
Hi, I know you added the ISW-ZPR1-WP13 to your driver, but how can I get the ISW-ZDL1-WP11G to work? Before switching to edge, I used the same config (IDE?) for them. Oddly enough, they just stopped working on 7/21.

Thanks in advance.

**Comment by Mariano-Github** [comment]
Hi,

Added to this driver version with same configurations of ISW-ZPR1-WP13

```
───────────────────────────────────────────────────
 Name         Zigbee Motion Sensor Mc
 Version      2023-08-02T17:15:24.51491913
───────────────────────────────────────────────────
 id: "Bosch-ISW-ZDL1-WP11G-Motion"
    deviceLabel: Bosch Motion Sensor
    manufacturer: Bosch
    model: ISW-ZDL1-WP11G
    deviceProfileName: motion-temp-battery
```

**Comment by Hawk15000** [comment]
Thank you so much! Will give it a go when I get home.
