### ISSUE TITLE
Tuya TS0202 motion sensor sensitivity

### ISSUE THREAD

**Issue by coinzdude** [Mariano-Github/Edge-Drivers-Beta#87]
I'm having an issue getting this sensor to trigger more easily. Can we adjust the sensitivity for this motion sensor, and is this the right setting?  What values would I use?

![image](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/58857646/a11abf87-916a-45d7-8313-e7b16b2abfa9)

Thank you so much for this work!

**Comment by Mariano-Github** [comment]
Hi,
This device does not have sensitivity adjustment.

That preference only informs that version 5 incorporates those sensitivity adjustments in the devices that support it.

**Comment by coinzdude** [comment]
Thank you for the information!
