### ISSUE TITLE
Fingerprint for zigbee smoke detector _TZE200_m9skfctm 

### ISSUE THREAD

**Issue by donovanma** [Mariano-Github/Edge-Drivers-Beta#89]
Hi, newby here but starting to learn Edge.  Bought two smoke detectors that only pair as Zigby Things.  The Smartthings Beta driver lists this manufacturer and model but the driver doesn’t appear for the device.

here is the info dump from the device from your Zigbee driver:

<img width="367" alt="image" src="https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/44532395/0b26fffc-9dce-4794-a6a7-e9fb3afc8cb3">
 
 Am I doing something wrong getting the smoke detector driver to appear?

thanks so much

**Comment by Mariano-Github** [comment]
Hi,

This device use TUYA cluster EF00 and does not work with standard zigbee drivers.
Yo can use personal EF00 devices driver
https://community.smartthings.com/t/st-edge-personal-tuya-devices-generic-ef00-device/255270?u=mariano_colmenarejo

**Comment by donovanma** [comment]
Thanks so much, works great!  

I appreciate the information!
