### ISSUE TITLE
MIR-SM100-TY Smoke sensor 

### ISSUE THREAD

**Issue by ohbotya** [Mariano-Github/Edge-Drivers-Beta#90]
Hi! Added successfully, but every 1:40 I saw offline message , can you change request interval and fix this problem?
![IMG_3088](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/80760841/624254e3-c9fd-4539-8572-250601e0f3ee)

**Comment by Mariano-Github** [comment]
Hi,

try with this driver version

You need uninstall device and reinstall it with new driver version

```
───────────────────────────────────────────────────
 Name         Zigbee Smoke/CO Detector Mc
 Version      2023-08-17T18:03:18.535855907        
───────────────────────────────────────────────────
```

**Comment by ohbotya** [comment]
![IMG_3132](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/80760841/6aeaeec0-33eb-415a-8ce3-1b7680b0f13f) it doesn’t work 🙁

**Comment by Mariano-Github** [comment]
Your driver version is 2023-08-15 prior to changes in the driver configuration

> try with this driver version
> 
> You need uninstall device and reinstall it with new driver version
> 
> ```
> ───────────────────────────────────────────────────
>  Name         Zigbee Smoke/CO Detector Mc
>  Version      2023-08-17T18:07:22.000078744        
> ───────────────────────────────────────────────────
> ```

Last version is 
Zigbee Smoke/CO Detector Mc
2023-08-21T10:26:23.32755445 

Try to unistall a re install with this version

**Comment by ohbotya** [comment]
Hi!
Done, but nothing changes 
![Uploading IMG_3214.jpeg…]()

**Comment by ohbotya** [comment]
![IMG_3213](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/80760841/d984b1b2-8e15-4d2c-8f16-8114d4d5d320)

**Comment by ohbotya** [comment]
![IMG_3214](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/80760841/9615c9cd-c2d7-4dd8-972d-351ab0ee1f19)

**Comment by Mariano-Github** [comment]
Hi,
If you send me logs with the CLI when the device is paired I can analyze what responds to the configuration and if it is done or not.

this is a tutorial to install CLI a capture logs
https://community.smartthings.com/t/edge-driver-or-device-handeler-for-a-tuya-zemismart-zigbee-plug-with-energy-mesurment-capabilities/245383/18
