### ISSUE TITLE
zigbee-motion-sensor-v4

### ISSUE THREAD

**Issue by celopez98** [Mariano-Github/Edge-Drivers-Beta#91]
Could you add the following signature to the Zigbee-motion-sensor-v4...

    deviceProfileName: motion-battery
  - id: "_TZE200_mgxy2d9f/ZG-204ZL"
    deviceLabel: Motion Sensor
    manufacturer: _TZE200_mgxy2d9f
    model: TS0601

Thanks.

**Comment by celopez98** [comment]
I think it does not. I'm trying to send you 2 photos of the instructions
butIguessIhavetoconvertthemtopdf. IfI'mableIwillsendthemsoon.

.It is a very simple device. Even the timing of the sensor is controlled by
dip switches.

**Comment by celopez98** [comment]
Enclosed are the instructions. Sorry it took me so long.
[CCF08172023.pdf](https://github.com/Mariano-Github/Edge-Drivers-Beta/files/12375711/CCF08172023.pdf)

**Comment by Mariano-Github** [comment]
Hi,

Try with this driver version
```
───────────────────────────────────────────────────
 Name         Zigbee Motion Sensor Mc
 Version      2023-08-18T18:19:22.533393514        
───────────────────────────────────────────────────
- id: "_TZE200_mgxy2d9f/SP2-ZB"
    deviceLabel: SP2-ZB Motion Sensor
    manufacturer: _TZE200_mgxy2d9f
    model: TS0601
    deviceProfileName:  motion-battery
```

**Comment by celopez98** [comment]
Thank you so much. Uninstalled and reinstalled driver and it worked like a charm. So glad you have made these drivers available to everyone.

Is it OK if I post for people to use your drivers in Amazon?

**Comment by Mariano-Github** [comment]
> Is it OK if I post for people to use your drivers in Amazon?

Hi,

Ok, The driver is open source, anyone who needs it can use it

**Comment by celopez98** [comment]
Thank you. You are much appreciated.
