### ISSUE TITLE
Fantem LED Stripe

### ISSUE THREAD

**Issue by SPAeotec** [Mariano-Github/Edge-Drivers-Beta#94]
Hi,

can you please add the Fantem LED Stripe ID. This is the same how Aeotec Stripe US. (Z-Wave Bulb)

![image](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/62385464/362dce90-53c2-46b5-a8e6-71f1088ed1a1)

Cheers 
Sebastian

**Comment by Mariano-Github** [comment]
Hi 
There are several Aeotec bulbs in the driver.

Do they have adjustable rgbw color temperature or just level?

**Comment by SPAeotec** [comment]
It is the exact same unit as this one:

Only the manufacturer has changed.:

- id: "AEOTEC_LED_STRIP_US"
  deviceLabel: Aeotec Light
  manufacturerId: 0x0086
  productType: 0x0103
  productId: 0x0079
  deviceProfileName: rgbw-bulb-3000K-8000K

LED Strip with Level and RGBW/WW

**Comment by SPAeotec** [comment]
Thanks

**Comment by SPAeotec** [comment]
We have tested it successfully.
